kubernetes-sigs/contributor-playground

paris/OWNERS

I'm giving a talk at the [Paris Open Source Summit](https://www.opensourcesummit.paris/). I want to use this repo to demonstrate how to contribute to Kubernetes.

add a new repo for a talk at the Paris Open Source Summit

---

seattle/intro.md

Added my introduction

---

bay-area-kube-day/README.md

Fixed the spelling of "KubeDay" and added a link to the
event schedule.

Improve Bay Area KubeDay README.

---

exercises/prs.md

Fixes instructions to require non-OWNERS entries to open the initial PRs.
/assign @jberkus

Add corresponding change in prs.md

---

shanghai/2019/OWNERS

Signed-off-by: Jason Plurad <pluradj@gmail.com>

Add pluradj to Shanghai 2019 approvers

---

cndt-2019/OWNERS

In a public event CloudNativeDays Tokyo, we have an upstream
training. This is for adding mentors.
Thank you, mentors.

Add cndt-2019/OWNERS for training in JP

---

cndt-2019/README.md

This PR adds README.md to folder of cndt-2019.
It's the start point for New Kubernetes Contributor Workshop.
None
```release-note
None
```
None

Add README.md to cndt-2019

---

ood-2019/OWNERS

In a public event Okinawa Open Days 2019, we have an upstream
training. This is for adding mentors to `OWNERS` file.
Thank you, mentors.
NONE
NONE
```release-note
NONE
```
/assign @guineveresaenger

Add ood-2019/OWNERS for training in JP

---

ood-2019/docs/attendee-prerequisites.md

Update and reorganize the instruction to prepare GitHub account and CNCF CLA.
It clarifies the instruction and the notice on the email address used.
```release-note
NONE
```

Update OOD2019 upstream training prerequisites instruction

---

kft-2020/OWNERS
kft-2020/README.md
kft-2020/docs/attendee-prerequisites.md
kft-2020/hands_on.md

We will hold Kubernetes upstream training In a public event Kubernetes Fetst Tokyo 2020(formerly [Kubernetes Community Day Tokyo 2020](https://kubernetescommunitydays.org/events/2020-tokyo/)).
This PR adds work place folder for the event and some assets for training, and also OWNERS file.
None
None
```release-note
None
```

Add work folder for training on Kubernetes Fest Tokyo 2020

---

kft-2020/README.md

This PR changes event name from "Kubernetes Fest Tokyo 2020" to "KubeFest Tokyo 2020", because that canonical name for it has been decided to "KubeFest Tokyo 2020".
NONE
NONE
```release-note
NONE
```
NONE

Change event name to KubeFest Tokyo 2020

---

kft-2020/docs/attendee-prerequisites.md

Developer should check the company policy before joining workshop to contribute.
This commit adds this.
Fixes #
```release-note
```
```docs
```

Add checking company policy before joining workshop

---

cndt-2020/OWNERS
cndt-2020/README.md
cndt-2020/docs/attendee-prerequisites.md
cndt-2020/hands_on.md
cndt-2020/workdir/toyoda.md

We will hold Kubernetes upstream training In a public event CloudNative Days Tokyo 2020.
This PR adds work place folder for the event and some assets for training, and also OWNERS file.
NONE
NONE
```release-note
NONE
```
NONE

Add folder for cndt-2020

---

japan/assets/attendee-prerequisites.md

This PR updates prerequisites page on Japan event.
Update contents for ease reading on attendee by converting to desu/masu style, mainly.
And update some items(emphasize items, add details etc..).
Related to: #635

Update prerequisite on japan folder

---

japan/cndo-2021/README.md
japan/cndt-2019/README.md
japan/cndt-2020/README.md
japan/kft-2020/README.md
japan/ood-2019/README.md

This PR extracts facilitators list from slide file to `README.md` on each Japan event.
As of now, facilitators list is included in workshop slide file.
It's good to extract informations which depends on each event to `README.md`, because that workshop slide for Japan event was moved to `japan/assets` folder as common asset.

Extract facilitators from slide to README on Japan

---

japan/cndo-2021/README.md

This PR adds items following to `README.md` in cndo-2021:
- Slack name for each facilitator
- Timetable for the event

Add slack name to README in cndo-2021

---

japan/cndo-2021/README.md

This PR moves date description of training to timetable section.
We has created timetable section recently, so it's appropriate to collect in that section about datetime.

Move holding date to timetable in cndo-2021

---

japan/adhoc/README.md

This PR adds index for training video to `README` on `japan/adhoc`.
It will be more ease to watch the video.
NONE
NONE
```release-note
NONE
```

Add video index for adhoc training in japan folder

---

japan/OWNERS

/kind cleanup
/kind feature
This PR adds oomichi to OWNERS on `japan/` as reviewer and approver.
Recently he acts as collaborator on this repository.
None
None
```release-note
NONE
```
None

Add oomichi to OWNERS on japan folder

---

brazil/OWNERS
brazil/README.md
brazil/attendee-instructions.md

/kind feature
Together with @rikatz we are planning to do a New contributor workshop in Brazil in the upcoming months and this PR is the setup for the directory to hold the playground.
I think we need to translate to PT-BR the `brazil/attendee-instructions.md` but I can do it in a follow up
/assign @nikhita @rikatz
Fixes #
```release-note
brazil: add initial directory to hold the NCWs in Brazil
```
```docs
```

brazil: add initial directory to hold the NCWs in Brazil

---

japan/README.md

/kind cleanup
To see future trainings easily, this adds the schedule.
```release-note
NONE
```
```docs
```

Add coming upstream training schedule in Japan

---

remote/README.md
remote/learners/shu-mutou.md

To avoid conflicting PRs, add the `<your github account>.md` file to the `learners/` directory instead of adding your github account to the `OWNERS` file.
Fixes #
```release-note
NONE
```
```docs
```

Add `learners/` directory, to avoid conflict

---

japan/README.md

>
Fix typo
Fixes #
```release-note
NONE
```
```docs
```

Fix typo in README in `japan`

---

japan/assets/attendee-prerequisites.md

/kind cleanup
This PR removes a description which explains moving to EasyCLA.
EasyCLA is general process for signing the CLA at now, we can remove this description.
None
None
```release-note
NONE
```
None

Remove odl description about EasyCLA in japan folder

---

OWNERS

Follow up AI from ContribEx Maintainers track (at KubeCon EU 2025)
Discussed offline with the current OWNERS.
cc: @kubernetes-sigs/sig-contributor-experience-leads

add shu-mutou as root OWNERS
