denver/OWNERS

SO that they can try out LGTMing things

Add workshop participants to denver OWNERs

---

denver/carlisia.md

Per Gophercon Kubernetes contributor workshop. Closes #2.

Add about me file for carlisia

---

denver/evillgenius75.md

Merging my pull request for intro file. Satisfies Issue #4

Evillgenius75 intro file

---

denver/matthewbrahms.md

Adding intro for matthewbrahms

Issue3: Adding intro file for matthewbrahms

---

denver/TheGhostHuCodes.md

As a part of the gophercon 2018, adding an introduction markdown file to
the denver folder of this repo.
Satisfies Github issue #6

Add introduction file for TheGhostHuCodes

---

shanghai/hello.md

hello, shanghai!

---

shanghai/OWNERS
shanghai/hello-from-table-x.md

Add hello from table X

---

shanghai/knock-knock.md

Hello everyone

---

shanghai/thomas.md

Tomeyday's first commit for PR testing in Shanghai

---

shanghai/OWNERS

add my self to the owner list
/assign @jberkus

Add myself to the owner list

---

shanghai/OWNERS

fix quietcoolwu name

---

shanghai/OWNERS
shanghai/hello-kubernetes.md

Signed-off-by: jojohappy <sarahdj0917@gmail.com>

New test PR

---

shanghai/k8s_is_great.md

Add a file

---

shanghai/hello-shanghai.md
shanghai/thomas.md

interesting

---

exercises/README.md
exercises/issues.md

Also updates issue exercise
/assign @jberkus

Adds README describing the purpose of the exercises/ folder

---

seattle/OWNERS

Yay let's do pull request practice!

Adding OWNERS for workshop

---

seattle/OWNERS

/cc @guineveresaenger
/assign @tpepper @jberkus

Add idealhack as an approver at NCW Seattle

---

seattle/README.md

Correcting typo in README.md

---

seattle/README.md

fixing readme typo

---

seattle/README.md

Fix typo ("worshop" to "workshop") in seattle/README.md

Fix typo in seattle/README.md

---

seattle/table1.md

Table 1 PR exercise

---

seattle/workshop-prerequisites.md

add prerequisites files

---

seattle/ppl/gitbytes.txt

here is an example new file that can be deleted at any time

---

seattle/cchengleo

PR-practice

---

seattle/cat-poems/She-Sights-a-Bird-Emily-Dickinson.md

Added new beautiful poeam

---

seattle/anton.md

FIX: mine intro

---

beijing/OWNERS
beijing/README.MD

Hello Beijing

---

bay-area-kube-day/OWNERS

Blah Blah Blah…
Because Blah Blah Blah

BayArea KubeDay new members

---

OWNERS
OWNERS_ALIASES
bay-area-kube-day/OWNERS
beijing/OWNERS
denver/OWNERS
paris/OWNERS
seattle/OWNERS
shanghai/OWNERS
shanghai/qiniu/OWNERS

Updated OWNERS files to use go.k8s.io for pointing to docs

---

barcelona/OWNERS

Lubomir is helping with the new contributor workshop for Barcelona.
Signed-off-by: Tim Pepper <tpepper@vmware.com>

add Lubomir to Barcelona OWNERS file

---

barcelona/README.md

Update the location of the New Contributor Summit from Seattle to Barcelona

Update the location of the New Contributor Summit

---

barcelona/hejhej.md

Hello world from Swedish contributors.

Greetings from Sweden

---

barcelona/201.md

Missing comma at 201.md file

---

barcelona/testPR.md

Hello from Diversity lunch of Kube con

---

barcelona/README.md

Change Seattle to Barcelona in README.md

Change Seattle to Barcelona in README.md

---

barcelona/eveything-is-awesome.txt

:smile: TODO Fix spelling mistake!

added eveything-is-awesome.txt

---

barcelona/README.md

Signed-off-by: pamela-kelly <pamelakelly7@gmail.com>
This PR adds the date of the workshop to the README

Adding the date of the workshop to the README

---

barcelona/prettyPR.md

my pretty PR

---

seattle/test.md

My First PR.

---

barcelona/myfile.md

my first pull request

---

shanghai/2019/OWNERS

Signed-off-by: Pang Yan Han <pangyanhan@gmail.com>

Add myself to Shanghai approvers list

---

shanghai/2019/prtrial.md

my test pr

---

shanghai/2019/Dockerfile

I made the following change
- add nginx Dockerfile 
The reason is that everyone loves nginx!

Add nginx Dockerfile

---

shanghai/2019/pr-test.md

update pr-test.md for pull request test

update pr-test.md for pull request test

---

shanghai/2019/README.md

Update the README with the correct year!
/sig docs

Update the year in KubeCon Shanghai 2019 README

---

shanghai/2019/README.md

Fix year number in the title

---

shanghai/2019/OWNERS

Add ashahab to OWNERS

---

shanghai/2019/new_feature.go

this is a new feature

---

shanghai/2019/test.txt

my test pull request

---

shanghai/2019/new_feature.go

add a hello words for test PR

---

OWNERS

I'd like to help shepherd things here.
/assign @parispittman

Add nikhita as approver

---

cndt-2019/README.md

Add slides for cndt-2019

---

cndt-2019/gopher.md

>
> /kind bug
> /kind design
> /kind flake
Add gopher.md
```release-note
NONE
```

Add gopher.md to cndt-2019.

---

cndt-2019/mumoshu.test.txt

/kind cleanup
Removes the fake contents added via #362 to finish my upstream training.
There's no specific issue related to this :)
- Thanks for your support. I'm feelin easier than ever to start contributing k/k!

Finish my upstream training

---

ood-2019/README.md
ood-2019/docs/attendee-prerequisites.md
ood-2019/workdir/shu-mutou.md

>
> /kind bug
> /kind design
> /kind flake
Add initial documentations for OOD-2019
None
@atoato88 
```release-note
NONE
```
```docs
```

Add initial contents for OOD 2019

---

ood-2019/docs/attendee-prerequisites.md

This PR adds detailed texts to `attendee-prerequisites.md` on ood-2019.
NONE
NONE
```release-note
NONE
```
NONE
/assign @shu-mutou

Update attendee-prerequisites.md on ood-2019

---

sandiego/OWNERS
sandiego/README.md

Add San Diego Workshop folder

---

sandiego/OWNERS

Update San Diego OWNERS with random intro contributors.

---

sandiego/README.md

According to the instructions, we are supposed to add something this file. 
Please see example KEP, or issue#, etc. etc.

Add Room 15's change

---

sandiego/README.md

Added "have fun" for README for the new contributor workshop

Add "have fun" 

---

sandiego/README.md

According to the request, name has been added to the readme file.

adding name to the readme

---

ood-2019/docs/attendee-prerequisites.md

This commit adds a task to register to slack in ood-2019.
NONE
NONE
```release-note
NONE
```
NONE
/assign @shu-mutou

Add task to register to slack in prerequisite in ood-2019

---

ood-2019/README.md

This PR adds a presentation slide to ood-2019.
NONE
NONE
```release-note
NONE
```

Add a presentation slide to ood-2019

---

ood-2019/workdir/foo.md

/kind bug
Add foo.md for training.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

Add foo.md

---

ood-2019/workdir/masaru-oki.md

Add self introduction text for training.
Fixes #
```release-note
NONE
```
```docs
```

Add masaru-oki.md

---

ood-2019/workdir/khrd.md

This is a PR test.
I added the "khrd.md" for my training.
```release-note
NONE
```
/pony Twilight Sparkle

Add khrd.md

---

ood-2019/hands_on.md

/kind feature
Add hans_on.md
Fixes #
```release-note
NONE
```
```docs
```

Add hands_on.md

---

ood-2019/workdir/y_nishimura.md

/kind bug
Add y_nishimura.md for training.
Fixes #
```release-note
NONE
```
```docs
/sig testing
```

Add y_nishimura.md

---

ood-2019/workdir/keruru.md

Fixes #
I did it again.
```release-note
```
```docs
```

add keruru.md

---

ood-2019/workdir/atoato88.md

This PR adds note for atoato88's.
NONE
```release-note
NONE
```
NONE

Add my note to ood-2019

---

barcelona/myprfile.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

My first pr in contributor playground

---

kft-2020/docs/attendee-prerequisites.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add link to code of conduct

---

kft-2020/docs/attendee-prerequisites.md

/kind cleanup
This improves attendee-prerequisites.md for kft-2020.
Fixes #
```release-note
NONE
```
```docs
```

Update attendee-prerequisites.md for kft-2020

---

kft-2020/hands_on.md
kft-2020/workdir/toyoda.md

This creates workdir directory and updates hands_on.md for kft-2020.
Fixes #
```release-note
NONE
```
```docs
NONE
```

Create workdir and update hands_on.md for kft-2020

---

kft-2020/README.md

This PR adds a link of event schedule to README.md
NONE
NONE
```release-note
NONE
```
NONE

Add event shedule url to README.md

---

kft-2020/workdir/foo.md

This adds foo.md for kft-2020.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

Add foo.md for kft-2020 workshop

---

kft-2020/workdir/hichihara.md

This patch adds hichihara.md for kft-2020 workshop.
```release-note
NONE
```
```docs
```

Add hichihra.md for kft-2020 workshop

---

kft-2020/workdir/gky360.md

This adds gyk360.md for kft-2020.
Fixes #
```release-note
NONE
```
```docs
```

Add gky360.md for kft-2020 workshop

---

kft-2020/workdir/eba.md

This adds eba.md for kft-2020 workshop.
Fixes #
```release-note
NONE
```
```docs
```

Add eba.md for kft-2020 workshop

---

kft-2020/workdir/bells17.md

Fixes #
```release-note
None
```
```docs
```
/sig testing

Add bells17.md for kft-2020

---

kft-2020/workdir/degiple.md

This adds degiple.md for kft-2020.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

Add degiple.md for kft-2020 workshop by degiple

---

kft-2020/workdir/kimullaa.md

>
> /kind bug
> /kind design
> /kind flake
This adds kimullaa.md for kft-2020.
Fixes #
NONE
```release-note
```
```docs
```

add workshop impression

---

kft-2020/workdir/yktsubo.md

Add yktsuboi.md file for kft-2020
Fixes #
```release-note
NONE
```
```docs
```

Add yktsubo.md for kft2020 workshop.

---

kft-2020/workdir/rkgy.md

add file for kft-2020 workshop
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

add rkgy.md for kft-2020 workshop

---

kft-2020/workdir/tkms0106.md

Add documentation to `kft-2020/workdir`
No issue
NONE
```release-note
NONE
```
```docs
NONE
```

Add tkms0106.md

---

kft-2020/workdir/nnasaki.md

for KubeFest Tokyo 2020 - Kubernetes アップストリームトレーニング
None
```release-note
```
```docs
```

Add nnasaki.md

---

kft-2020/workdir/translucens.md

Add translucens.md
Fixes #
```release-note
NONE
```
```docs
```

Add translucens.md

---

kft-2020/workdir/thanks.md

Add thanks.md for kft-2020 workshop
Fixes #
```release-note
NONE
```
```docs
```

Add thanks.md for kft-2020 workshop

---

kft-2020/workdir/waiwai.md

Add waiwai.md file for kft-2020
Fixes #
```release-note
NONE
```
```docs
```

Add waiwai.md for kft-2020 workshop

---

kft-2020/workdir/faruryo.md

Kubernetesコントリビューティング練習のためのファイル追加
Fixes #
```release-note
NONE
```
```docs
```

add faruryo.md for kft-2020 workshop

---

kft-2020/workdir/rkasa.md

I added rkasa.md file.
This change is needed for kft-2020 workshop.
Fixes #
```release-note
NONE
```
```docs
```

Add rkasa.md for kft-2020 workshop

---

kft-2020/workdir/add_ushi_foo_md

Fixes #
```release-note
NONE
```
```docs
```

Add add_ushi_foo_md

---

kft-2020/workdir/mizumoto.md

This adds mizumoto.md for kft-2020.
Fixes #
```release-note
NONE
```
```docs
```

Add mizumoto.md for kft-2020

---

kft-2020/workdir/eto.md

Fixes #
```release-note
NONE
```
```docs
```

Add eto.md

---

remote/LEARNERS
remote/README.md

Remote directory is for all those who are learning through youtube videos and blogs

Add remote directory

---

OWNERS

/assign @mrbobbytables @castrojo

Update OWNERS to reflect current contribex leads

---

remote/LEARNERS

Hey look, it's my first pull request and I added myself to a list.
>
> /kind bug
> /kind design
> 
> /kind flake
This PR helps me learn how the process works so I can be more helpful in the future.
```release-note
```
```docs
```

Add Erik Arneson to remote learners list

---

CONTRIBUTING.md

> /kind bug
The original link https://git.k8s.io/community/contributors/guide/contributor-cheatsheet.md referred by `Contributor Cheat Sheet` is no longer available (404). It should point to a multilingual directory now.
```release-note
```
```docs
```

The previous link should point to a multilingual directory now

---

cndt-2020/docs/attendee-prerequisites.md

This PR removes prequisite items about golang and docker, because these items are optional for additional excercise.
We will move these items to a slide, not attendee prerequisites page.
NONE
NONE
```release-note
NONE
```
NONE

Update attendee-prerequisites in cndt2020

---

cndt-2020/workdir/inami.md

To complete cndt-2020 workshop.
Fixes #
```release-note
None
```
```docs
```

Add inami.md for demo

---

cndt-2020/workdir/bo0km4n.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

[Fix/Docs] Add bo0km4n markdown for demo

---

cndt-2020/workdir/naotospace.md

Fixes #
```release-note
NONE
```
```docs
```

Add naotospace.md for exercise

---

cndt-2020/workdir/yuhara.md

Add yuhara.md into cndt-2020 for demo.
Fixes #
```release-note
NONE
```
```docs
```

Add yuhara.md

---

cndt-2020/workdir/akitok.md

Add akitok.md into cndt-2020 for demo.
Fixes #
```release-note
NONE
```
```docs
```
/pony

Add akitok.md for demo

---

cndt-2020/workdir/renjikari.md

Add renjikari.md into cndt-2020 for demo!
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

Add renjikari md

---

cndt-2020/workdir/tsubasaxzzz.md

Add tsubasaxzzz.md into cndt-2020 for demo.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/pony

Add tsubasaxzzz.md

---

cndt-2020/workdir/rueyjye.md

Add demo file for CloudNative Days Tokyo 2020 upstream training hands-on.
Fixes #
```release-note
NONE
```
```docs
```

add practice demo file

---

cndt-2020/workdir/shimada.md

Add shimada.md into cndt-2020 for demo.
Fixes #
```release-note
NONE
```
```docs
```

add shimada.md

---

cndt-2020/workdir/shuzokato.md

To complete cndt-2020 workshop.
Fixes #
```release-note
None
```
```docs
```

add shuzokato.md

---

cndt-2020/workdir/mfykmn.md

For practicing PR
Fixes #
```release-note
NONE
```
```docs
```

Add mfykmn.md

---

cndt-2020/workdir/ymurase.md

Add ymurase.md into cndt-2020 for demo.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/pony
/joke
/shrug
/unshrug

Add ymurase.md

---

cndt-2020/workdir/masakihara.md

Add masakihara.md into cndt-2020 for training.
Fixes #
```release-note
NONE
```
```docs
```
/pony

Add masakihara.md for training.

---

cndt-2020/workdir/yassan.md

for Kubernetes upstream training in CNDT2020
Fixes #
```release-note
NONE
```
```docs
```

Add yassan.md for Kubernetes upstream training in CNDT2020

---

cndt-2020/workdir/mochizuki875.md

Add hands-on doc cndt-2020/workdir/mochizuki875.md.
Fixes #
```release-note
NONE
```
```docs
```

add mochizuki875.md

---

cndt-2020/workdir/micheam.md

Add sample file into `cndt-2020/workdir`.
Fixes #
Thank you for a wonderful workshop ❤️ 
```release-note
NONE
```
```docs
```

Add micheam.md

---

cndt-2020/workdir/katsuhisakitano.md

add katsuhisakitano.md for kubernetes upstream training.
Fixes #
```release-note
NONE
```
```docs
```
/pony

add katsuhisakitano.md for kubernetes upstream training

---

cndt-2020/workdir/nao-ri_commnet.md

>
nao-ri_commnet.md into CNDT2020 for demo 
Fixes #
```release-note
NONE
```
```docs
```
size/XS

nao-ri_commnet.md for demo

---

cndt-2020/workdir/amomsi.md

This PR is just a part of the contribution workshop.

This my greeting contribution

---

japan/README.md

Added history into README and announcement for new event would be added here.

Add history in `japan`

---

OWNERS

Ref: https://github.com/kubernetes/community/issues/5442
/hold
until https://github.com/kubernetes/community/pull/5443 merges
/cc @alisondy @castrojo @mrbobbytables 
/assign @mrbobbytables

Add alisondy as sig-contribex co-chair

---

india/OWNERS
india/README.md
india/k8s-blr-2021/OWNERS
india/k8s-blr-2021/README.md
india/k8s-blr-2021/attendee-instructions.md

Taking inspiration from the Japan directory - https://github.com/kubernetes-sigs/contributor-playground/tree/master/japan
(thanks for having such clear docs @atoato88 @k-toyoda-pi @shu-mutou @s-ito-ts!)
/assign @palnabarun @divya-mohan0209

india: init k8s bangalore contributor workshop

---

india/k8s-blr-2021/README.md
india/k8s-blr-2021/workdir/example.md

- Adds `workdir` directory and example file. Will create another file during the walkthrough in the meetup.
- Fix link for attendee-instructions.md
/assign @palnabarun @divya-mohan0209

india/k8s-blr-2021: add workdir dir and example file

---

india/k8s-blr-2021/README.md

Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>
/cc @divya-mohan0209 @nikhita

k8s-blr-2021: update slides URL

---

india/k8s-blr-2021/workdir/nikhita.md

Adding a PR for the k8s blr meetup

Add nikhita.md

---

india/k8s-blr-2021/workdir/woof.md

Signed-off-by: Abhishek Mishra <geekabhi@outlook.com>
A test PR 🐶

Add woof.md (k8s blr workshop )

---

india/k8s-blr-2021/workdir/dinesh_kumar.md

added new user

---

india/k8s-blr-2021/workdir/rtnpro.md

Hands on contributor playground
NONE
NONE
NO

Added rtnpro.md.

---

india/k8s-blr-2021/workdir/cool_new_feature.md

Added a new file.
/kind feature

Added something new

---

india/k8s-blr-2021/workdir/rbt.md

> /kind feedback
Giving nice feedback for Kubernetes Contributor meetup :) 
Thanks a lot !!

RBT Feedback. Adding rbt.md

---

india/k8s-blr-2021/workdir/mahendra.md

Add feedback in a file

---

india/k8s-blr-2021/workdir/hussaina.md

For learning commit process
None
```release-note
```
```docs
```

Add hussaina.md

---

india/k8s-blr-2021/workdir/K8sIsAwesome.md

Declaring that K8s is awesome

---

india/k8s-blr-2021/workdir/prabhu.md

Added a new file
/kind feature
/assign @palnabarun

Add prabhu.md

---

india/k8s-blr-2021/workdir/srinivasakartheek.md

First of many times

---

india/k8s-blr-2021/workdir/feedback_arjun.md

/kind feature
Feedback for the session :)

Added feedback from arjun921

---

india/k8s-blr-2021/workdir/rajeev.md

New Learning on creating a PR!

Add rajeev.md

---

india/k8s-blr-2021/workdir/anubhav.md

Added a sample PR to get acquited to the the k8s PR flow

Add sample markdown file

---

india/k8s-blr-2021/workdir/daemon1024.md

Getting acquainted with the k8s workflow, part of the hands on session.
NONE
NONE

add daemon1024.md

---

india/k8s-blr-2021/workdir/grpit.md

Adds a review
Thank you all.
No

Review Added !!

---

india/k8s-blr-2021/workdir/mehul.md

>
added mehul.md
Fixes #
```release-note
```
```docs
```

initial commit

---

india/k8s-blr-2021/workdir/sourabhdeshmukh.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add sourabhdeshmukh.md

---

india/k8s-blr-2021/workdir/varen.md

/kind feature
Feedback for the session

Added feedback from Varen

---

india/k8s-blr-2021/workdir/akash.md

Hello, Kubernetes!

---

india/k8s-blr-2021/workdir/why-fixing-bugs-is-a-good-start.md

/kind feature
Adds info on why fixing bugs are a good start when contributing to open source projects
It solves the issue of people asking how can they contribute to open source, when they don't have much preferences and are out in the wild without direction
Will I get the swag? :P I'll add it to my closet of swags 🙈
No
Not Applicable

add doc on why fixing bugs is a good start

---

india/k8s-blr-2021/workdir/yudocaa.md

Signed-off-by: Sayan Chowdhury <sayan.chowdhury2012@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Hola, K8s!

---

india/k8s-blr-2021/workdir/recursion.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add recursion.md

---

india/k8s-blr-2021/workdir/yashraj.md

This is my first PR. Thanks for the awesome session guys.

fisrt commit

---

india/k8s-blr-2021/workdir/Awesome session.

Great session.

---

india/k8s-blr-2021/workdir/anjul.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

fixed location

---

japan/assets/hands_on.md

hands_on.md of japan contains the following line.
```
$ cd <EVENT-NAME>/workdir/
```
This file targets to japan user. So, we should add japan directory.
Fixes #
```release-note
NONE
```

Update hands_on.md of japan

---

japan/cndo-2021/workdir/foo_hide27k.md

Add foo_hide27k.md for cndo-2021 demo.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

Add foo_hid27k.md for cndo-2021 demo

---

japan/cndo-2021/workdir/shimodatkh.md

Add shimodatkh.md into for cndo-2021 contribution training.
```release-note
NONE
```
```docs
```

Add shimodatkh.md

---

japan/cndo-2021/workdir/hourglasshoro.md

Add hourglasshoro.md for cndo-2021 demo.
Fixes #
```release-note
NONE
```
```docs
```

Add hourglasshoro.md in cndo-2021

---

japan/cndo-2021/workdir/ryusa.md

Add ryusa.md
This PR is demo PR for japan/cndo-2021! 
Fixes #
```release-note
NONE
```
```docs
Thank you cndo-2021 !! 
```

Add japan/cndo-2021/ryusa.md for demo

---

japan/cndo-2021/workdir/add_kzk_test.md

add `add_kzk_test.md` in `japan/cndo-2021/workdir` for demo.
Fixes #
```release-note
NONE
```
```docs
```

add kzk_test.md for demo

---

japan/cndo-2021/workdir/fiz2buz.md

Fixes #
```release-note
NONE
```
```docs
```
/sig-testing

Add fiz2buz.md for cndo-2021 demo

---

japan/cndo-2021/workdir/chez-shanpu.md

Add `chez-shanpu.md` for cndo2021 hands-on
Fixes #
```release-note
NONE
```
```docs
```

Add chez-shanpu.md for cndo2021

---

japan/cndo-2021/workdir/udomomo_sample.md

Add `udomomo_sample.md` for cndo-2021 
Fixes #
```release-note
NONE
```
```docs
```

add udomomo_sample.md

---

japan/cndo-2021/workdir/eiiches.md

Add eiiches.md for CNDO-2021 training
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

Add eiiches.md for CNDO-2021 training

---

japan/cndo-2021/workdir/foo_y-taka-23.md

Add a dummy file for CNDO2021 upstream training
Fixes #
```release-note
NONE
```
```docs
```

Add foo_y-taka-23.md for cndo-2021 demo

---

japan/cndo-2021/workdir/shien3.md

Fixes #
```release-note
NONE
```
```docs
```

Add shien3.md for cndo-2021.

---

japan/adhoc/workdir/kos31de.md

Because of contribution test.
Fixes #
```release-note
NONE
```
```docs
```

Add kos31de.md

---

japan/adhoc/README.md

Add README.md for `japan/adhoc` folder

---

japan/README.md
japan/adhoc/README.md

Also, describe `adhoc` subfolder into `/japan/README.md`.

Add link to youtube for self-study into `/japan/adhoc`

---

japan/adhoc/workdir/ocuto.md

This PR is for my training.
Add ocuto.md. / To understand the kubernetes workflow.
N/A
NONE
```release-note
NONE
```
```docs
NONE
```

Add ocuto.md

---

india/k8s-blr-2021/workdir/p0r7m.md

> 
Contribution guidelines check
Fixes #
```
NONE
```
```
```

Add p0r7m.md

---

india/k8s-blr-2021/workdir/prasad.md

I am using this PR to test the PR workflow. 
```release-note
NONE
```
/woof

Add prasad.md

---

remote/LEARNERS

Add myself to remote LEARNERS
None
None
```release-note
None
```
None

Add palnabarun to remote/LEARNERS

---

india/kcd-blr-2021/OWNERS
india/kcd-blr-2021/README.md
india/kcd-blr-2021/attendee-instructions.md
india/kcd-blr-2021/workdir/palnabarun.md

Initialize workspace for workshop at KCD BLR
None
None
```release-note
NONE
```
None
/assign @nikhita

india: initialize workspace for workshop at KCD BLR

---

india/kcd-blr-2021/README.md

Signed-off-by: Madhav Jivrajani <madhav.jiv@gmail.com>
Add description for myself as a facilitator for KCD Bangalore 2021
```release-note
NONE
```
```docs
```
/assign @palnabarun

add description for Madhav Jivrajani in facilitators for kcd-blr-2021

---

india/kcd-blr-2021/README.md

Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

adding arsh in kcd 2021 facilitators

---

india/kcd-blr-2021/workdir/palnabarun.md

Update palnabarun's workdir snapshot
None
None
```release-note
NONE
```
```docs
NONE
```

kcdblr: Update palnabarun workdir

---

india/kcd-blr-2021/workdir/vikramcse.md

Update to vikramcse workdir
None
None
```release-note
None
```
```docs
None
```

update vikramcse workdir

---

india/kcd-blr-2021/workdir/avinash.md

>
> /kind bug
> /kind design
> /kind flake
Adds Avinash's introduction. Not too sure why you would need it haha
null
```release-note
NONE
```
```docs
N/A
```

india: avinash init

---

india/kcd-blr-2021/workdir/pavanraga.md

Update pavanraga's workdir snapshot
None
None
None
None

kcdblr: Update pavanraga workdir

---

india/kcd-blr-2021/workdir/rahulgrover99.md

Signed-off-by: Rahul Grover <rahulgrover99@gmail.com>
Update rahulgrover99's workdir snapshot
None
None
```release-note
NONE
```
```docs
NONE
```

kcdblr: Add rahulgrover99 workdir

---

india/k8s-blr-2021/workdir/vijaygenius123.md

Add india/workdir/vijaygenius123

---

india/kcd-blr-2021/workdir/palnabarun.md
india/kcd-blr-2021/workdir/sneha_k.md

Update sneha_k workdir
None
None

added file.

---

india/kcd-blr-2021/workdir/akshay.md

Add akshay.md in workdir
None
None
```release-note
None
```
```docs
None
```

kcdblr: Add akshay.md file to kcd-blr-2021 workdir

---

india/kcd-blr-2021/workdir/sachin.md

added my first PR to Kubernetes
Fixes #
```release-note
```
```docs
```

kcdblr : added my .md file 

---

india/kcd-blr-2021/workdir/vibhorr.md

/kind-documentation
>
> /kind bug
> /kind design
> /kind flake
Playground fun
Fixes #
```release-note
```
```docs
```

Vibhor Rawat addition

---

india/kcd-blr-2021/workdir/Sachin.md

Commiting ..

---

india/kcd-blr-2021/workdir/VedantKakde.md

Update Vedant Kakde workdir snapshot
None
None
```docs
None
```

Added my workdir

---

india/kcd-blr-2021/workdir/VikasManohar.md

>
> /kind bug
> /kind design
> /kind flake
None
None
Fixes #
Thank you for the workshop
```release-note
No
```
```docs
None
```

Adding new markdown file

---

india/kcd-blr-2021/workdir/sameer.md

None
None
Fixes #
Thanks for this call.
```release-note
None
```
```docs
None
```

added workdir file sameer.md

---

india/kcd-blr-2021/sunish.md

Added new file
None
None 
```release-note
None
```
```docs
None
```

Adding the new file sunish.md

---

india/kcd-blr-2021/workdir/ragsarang.md

it merges my file into kubernetes-sigs repo
nothing now
No. it does not introduce a user-facing change
None
Thanks.

first commit ragsarang

---

india/kcd-blr-2021/workdir/shankarganesh.md

Doc
Fixes #
NONE
NONE
```docs
```

Documentation

---

india/kcd-blr-2021/workdir/vaibhavp.md

Testing PR

---

india/k8s-blr-2021/workdir/benson.md
india/kcd-blr-2021/workdir/benson.md

None
None
None
```release-note
None
```

Add benson.md

---

india/kcd-blr-2021/workdir/nagaraju.md
india/kcd-blr-2021/workdir/nlohia.md

first contribution

---

india/kcd-blr-2021/workdir/praveen.md

Updated **\india\kcd-blr-2021\workdir\nikunjbanker.md
None
Thanks for the awesome sessions
NONE
NONE

first PR to K8s

---

india/kcd-blr-2021/workdir/chetan.md

Updated **\india\kcd-blr-2021\workdir\chetan.md
None
Thanks
None

Initial PR

---

india/kcd-blr-2021/workdir/karl_dasan.md

Updated **\india\kcd-blr-2021\workdir\karl_dasan.md
None
None
None

Created karl_dasan.md

---

remote/LEARNERS

Fixes 
NONE
NONE
```release-note
NONE
```

First Commit

---

remote/ghc-osd-2021/OWNERS
remote/ghc-osd-2021/README.md
remote/ghc-osd-2021/attendee-instructions.md

@divya-mohan0209 and I are organizing a Kuberentes new contributor workshop at Grace Hopper Open Source Day event: https://opensourceday.anitab.org/agenda/session/570739
/assign @mrbobbytables @divya-mohan0209

remote: add ghc-osd-2021 dir

---

india/remote/OWNERS
india/remote/README.md
india/remote/learners/sample.md

bootstrap an india/remote directory for people coming in from recordings

---

remote/ghc-osd-2021/hanna-test.md

Add hanna-test.md as a test file for OSD 2021

Test commit from OSD 2021

---

remote/ghc-osd-2021/lakshya.md

test commit OSD

---

india/remote/learners/palnabarun.md

Just like that. @palnabarun wanted to enroll as a remote learner.
Fixes None
Just be kind.
```release-note
NONE
```
```docs
NONE
```
/cc @nikhita
/this-is-fine

add palnabarun as a remote learner in India

---

india/remote/OWNERS

Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

adding arsh to india/remote approvers

---

india/remote/OWNERS

Signed-off-by: Madhav Jivrajani <madhav.jiv@gmail.com>
Adds @MadhavJivrajani as OWNER to `india/remote` in lieu of conducting NCW type events in the near future 
None
None
```release-note
NONE
```
```docs
```
/assign @palnabarun

Add self to india/remote OWNERS

---

india/remote/learners/kkaranth.md

>
> /kind bug
> /kind design
> /kind flake
Just to add myself ( @knidhikaranth ) as a remote learner in India. :)
Fixes None
Please be kind :) I am new to open source contributions. Thank you! \(^.^)/
```release-note
None
```
```docs
```
/cc @nikhita @palnabarun

Add knidhikaranth as a remote learner in India

---

india/remote/learners/KUBDOC.md

@aveshag wanted to be a new learner
Fixes NONE
Please be Kind
```release-note
NONE
```

Add aveshag as a new learner in India

---

india/remote/learners/ritika.md

Ritika added to learners list. 
None
Thank you for reviewing.
No 
```release-note
None
```
```docs
None
```
/cc @palnabarun @nikhita

Ritika added to learners.

---

india/remote/learners/arsh_demo.md

Signed-off-by: RinkiyaKeDad <arshsharma461@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

commit message from live demo

---

india/remote/learners/pritish.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add Pritish As A Contributor

---

india/remote/learners/divyasri.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add divya as contributor

---

india/remote/learners/SnehaMallik.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

First PR to kubernetes

---

india/remote/learners/index.ts.md

Signed-off-by: sairaj <sairaj2119@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

first pr will go now

---

india/remote/learners/Rupesh.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add Rupesh as contributor

---

india/kcd-blr-2021/workdir/sachin.md
india/remote/learners/sjagini.md

>
None
Fixes #
Just be kind. 
```release-note
```
```docs
```

saikiran's 1st PR to kubernetes repo

---

india/remote/learners/Kamaljeet_demo.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

1st demo pull request

---

india/remote/learners/komal.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

starting with opensource.

---

india/remote/learners/bhanu.md

<!--  Thanks for sending a pull request!  Here are some tips for you:
for work
None
None
```
```docs
NONE
```

add bhanu as a remote learner in India

---

india/remote/learners/kmahimarun.md

learning open-source and K8S
None
Fixes #
Please be Kind
```release-note
```
```docs
```

learning open-source

---

india/remote/learners/paarth.md

no reason
None
Thanks for the session
```release-note
NONE
```
```docs
NONE
```
/cc @palnabarun

Added Paarth as a remote learner in India

---

india/remote/learners/sonu.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

"Adding myself as a remote learner"

---

india/remote/learners/varunr.md

wanted to enroll as a remote learner
Fixes none
Just be kind :)
```release-note
NONE
```
```docs
NONE
```
/this-is-fine

Add Varun R as a remote learner in India

---

india/remote/learners/bkhatri.md

Just like that, first demo contribution.
Fixes - None
Just be kind. 
```release-note
NONE
```
```docs
NONE
```
/this-is-fine

bkhatri_first_contribution

---

india/remote/learners/naishadhv.md

For learning purposes
Fixes # None
```release-note
NONE
```
/woof

Added naishadhv.md for learning purposes

---

india/remote/learners/yavar.md

Just like that
Fixes None
```release-note
```
```docs
```
/this-is-fine

Add Yavar as a remote learner please

---

india/remote/learners/shreyansh2809.md

Created one file shreyansh2809.md
None
Thanks for the review.
```release-note
None
```
```docs
None
```
/cc  @nikhita @palnabarun

first_commit

---

india/remote/learners/sonipa.md

Just like that want to be remote learner
Fixes #
Just be kind
```release-note
NONE
```
```docs
NONE
```
/this-is-fine

adding sonipa as remote learner in India

---

india/remote/learners/msikka.md

No reason
NONE
NONE
```release-note
NONE
```
```docs
NONE
```
/cc @palnabarun @nikhita

add msikka as a remote learner

---

india/remote/learners/anujeetc.md

>
> /kind bug
> /kind design
> /kind flake
Adding new Contributor to India/remote
NA
Fixes #
NA
**Special notes for your reviewer**: You're Amazing! Have a Nice Day!
```release-note
NONE
```
```docs
```
/this-is-fine

Added Anujeet Chatterjee as Contributor.

---

india/remote/learners/mbansal.md

Adding new contributor to india/remote
NA
Fixes #
NA
Have a nice day!!
NONE
```
```
/this-is-fine

adding new

---

india/remote/learners/cayush.md

Fixes #
```release-note
NONE
```
```docs
```
/woof

My first k8s contribution!

---

india/remote/learners/aniket.md

Add @aniketarkin as contributor
NONE
NA
NA
NA
/cc @nikhita  @palnabarun

Add Aniket as contributor

---

india/remote/learners/georgephilip.md

@georgephilif want to enroll as a remote learner 
Fixes None
Just be Kind 
```release-note
NONE
```
```docs
NONE
```
/woof

Added george as learner for k8s

---

india/remote/learners/ssivaprathee.md

@ssivaprathee want to enroll as a remote learner
Fixes None
Just be Kind
```release-note
NONE
```
```docs
NONE
```
/woof

Added Siva as a learner

---

india/remote/learners/shriamrut.md

Added file shriamrut.md to india remote learners

---

india/remote/learners/kganorkar.md

>
> /kind bug
> /kind design
> /kind flake
None
Fixes #
None
None
```release-note
```
None
```docs
```
/assign  @palnabarun

Kaushik Markdown Created

---

india/remote/learners/govila.md

Just like that
Fixes None
Just be kind.
```release-note
NONE
```
```docs
NONE
```
/this-is-fine

add govilakshat1998 as a remote learner in India

---

india/remote/learners/brindon.md

Fixes None
```release-note
None
```
```docs
None
```
/woof

This is Brindon's first Kubernetes Contribution

---

india/remote/learners/tanmaym.md

Just like that
Fixes #
Be kind to me.
None
/cc @nikhita
/this-is-fine

add tanmaym as a remote learner in India

---

india/remote/learners/rkailashramesh.md

Adds rkailashramesh as a remote learner from India
Fixes None
Testing out my first PR as a Kubernetes contributor on playground! Plx be nice!
/woof

Add rkailashramesh as a remote learner in India

---

india/remote/learners/vasundharas.md

Adds Vasundhara to the learner's list
NONE
In need of /approve and /lgtm
NO
```release-note
NONE
```
```docs
No documents needed
```
/cc  @palnabarun @RinkiyaKeDad
/this-is-fine

First commit to K8s Playground

---

india/remote/learners/AbhyudayDixit.md

Adds Abhyuday to the learners list
NONE
In need of /approve and /lgtm
```release-note
NONE
```
```docs
NO DOCUMENTS REQUIRED
```
/cc @palnabarun @nikhita @RinkiyaKeDad
/this-is-fine

My first K8S contribution

---

india/remote/learners/thakurso.md

Fixes None
Please add me as a remote learner
```release-note
NONE
```
```docs
NONE
```
/this-is-fine

Add thakurso as a remote learner

---

india/remote/learners/kselvamani.md

just like that @kselvamani want to enroll as a remote learner
Fixes None
Just be a kind
```release-note
NONE
```
```docs
NONE
```
/cc @nikhita  @palnabarun 
/woof

Kselvamani k8s

---

india/remote/learners/prmehta.md

Fixes None
Please add me as a remote learner
```release-note
NONE
```
```docs
NONE
```
/this-is-fine

Add prmehta as a remote learner in India

---

india/remote/learners/karank8.md

Just like that.
Fixes None
Please add me as a remote learner.
```release-note 
NONE
```
```docs
NONE
```
/this-is-fine

add karan07krs as a remote learner in India

---

india/remote/learners/pratibha.md

Pratibha wanted to enroll as remote learner.
Fixes None
Plz be kind.
```release-note
None
```
```docs
None
```

add pratibha as a remote learner

---

india/remote/learners/maheshwariak.md

Initial commit
Fixes None
Please add me as remote learner. I would try to learn and contribute to K8 Open Source.
NONE
```release-note
NONE
```
```docs
NONE
```
/cc @palnabarun  @nikhita 
/this-is-fine

add maheshwariak as a remote learner in India

---

india/remote/learners/metalcyanide.md

NONE
```release-note
NONE
```
```docs
NONE
```

add metalcyanide to learners in india

---

india/remote/learners/dakshberry121.md

@dakshberry121 wants to be enrolled as a remote learner.
Fixes none
Please be kind.
NONE
NONE
/cc @palnabarun 
/this-is-fine

add Daksh as a remote learner in India

---

india/remote/learners/sgourav.md

>
> /kind bug
> /kind design
> /kind flake
Initial commit
Fixes: None
Please add me as a remote learner. I would try to learn and contribute to K8 Open Source.
```release-note
NONE
```
```docs
```
/cc @palnabarun @nikhita 
/this-is-fine

sgourav first commit to kubernetes project

---

india/remote/learners/ashubhanshi.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add ashubhanshi as a remote learner in india

---

india/remote/learners/goyalaa.md

Initial Commit
Fixes: None
Please add me as remote learner. I am willing to learn and contribute to open source of K8s
```release-note
NONE
```
```docs
NONE
```
/this-is-fine

add Aakanksha as a remote learner in India

---

india/remote/learners/ksuwarna.md

@ksuwarna wanted to enrol as a remote learner!
NONE
Just be kind xD
```release-note
NONE
```
/cc @palnabarun @nikhita
/this-is-fine

Add Krithika as a remote learner

---

india/remote/learners/chopraan.md

Just like that. Wanted to add myself as remote learner
Fixes None
Just be Kind
```release-note
NONE
```
```docs
NONE
```
/this-is-fine

Add Chopraan as remote learner in India

---

india/remote/learners/satyamkr.md

Just that @skmuz001 want to enroll as remote learner
Fixes None
just be kind
```release-note
NONE
```
```docs
NONE
```
/cc @nikhita 
/ This is fine

Add satyamkr as a remote learner in INDIA

---

remote/LEARNERS

@z1cheng want to be added as a remote learner
Fixes None
Hi, could you please approve my first pull request? Thanks!
```release-note
None
```
```docs
None
```
/cc @nikhita @palnabarun
/this-is-fine

Add z1cheng as a remote learner

---

remote/hackillinois-osf-2021/OWNERS
remote/hackillinois-osf-2021/README.md
remote/hackillinois-osf-2021/attendee-instructions.md
remote/hackillinois-osf-2021/madhav.md

Seed Contributor Workshop Dir for UUIC Hackillinois
- Add attendee instruction
- Add README with agenda and intros of facilitators
- Seed OWNERS files
Fixes #
None
None
```release-note
NONE
```
```docs
```
/assign @palnabarun @nikhita 
/cc @RinkiyaKeDad @rajaskakodkar

Seed Contributor Workshop Dir for UUIC Hackillinois

---

india/remote/learners/Arul.md

Signed-off-by: Arul Ashri <arulashri22@gmail.com>
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

demo commit

---

aotearoa/OWNERS
aotearoa/Readme.md

Create a folder to help Kiwi's to contribute to Kubernetes!

---

japan/cndt-2021/workdir/foo.md

Add foo.md into cndt-2021 for demo.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

add foo.md for cndt-2021 demo

---

japan/cndt-2021/workdir/toricls.md

This is a PR created at the Kubernetes upstream training in CNDT 2021.
NONE
```release-note
NONE
```
```docs
```
/sig test-never-exists

add toricls.md

---

japan/cndt-2021/workdir/kuma.md

Fixes #
```release-note
NONE
```
```docs
```
/joke

add kuma.md for cndt2021 demo

---

japan/cndt-2021/workdir/riita10069.md

add riita10069.md into cndt-2021 for hands-on
```release-note
NONE
```
```docs
```
/sig testing

add riita10069.md into cndt-2021

---

japan/cndt-2021/workdir/care0717.md

This is a PR created at the Kubernetes upstream training in CNDT 2021.
Fixes #
```release-note
NONE
```
```docs
```
/trick-or-treat

Add care0717.md

---

japan/cndt-2021/workdir/rung-test.md

Add rung-test.md to cndt-2021
Fixes # Nothing :)
None
```release-note
NONE
```
```docs
```
/sig testing

Add rung-test.md to cndt-2021 (training)

---

japan/cndt-2021/workdir/kenken-ishiken.md

Add kenken-ishiken.md for demo
Fixes #
```release-note
NONE
```
```docs
```
/bark

add kenken-ishiken.md

---

japan/cndt-2021/workdir/initial-nj.md

/kind feature
add initial-nj.md for CNDT2021 demo
NONE
```release-note
NONE
```
```docs
```
/sig testing

add initial-nj.md for CNDT2021 demo

---

japan/cndt-2021/workdir/foo.md
japan/cndt-2021/workdir/foo_regmarmcem.md

Add a test file
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

Add foo_regmarmcem.md to cndt2021 

---

japan/cndt-2021/workdir/k-srkw-hello-k8s-community.md

add k-srkw-hello-k8s-community.md into cndt-2021 for hands-on
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/bark

Add k-srkw-hello-k8s-community.md

---

japan/cndt-2021/workdir/mosuke5.md

This is my first PR in CNDT2021
Fixes #
```release-note
NONE
```
```docs
- [Other doc]: https://kubernetes.io/docs/concepts/overview/what-is-kubernetes/
```
/sig testing

add mosuke5.md for demo

---

japan/cndt-2021/workdir/moguraion.md

>
Fixes #
```release-note
NONE
```
```docs
```
/joke
/hoge
/ok-to-test

Add moguraion.md

---

japan/cndt-2021/workdir/orimanabu.md

Fixes #
```release-note
NONE
```
```docs
```

Add orimanabu.md

---

remote/hackillinois-osf-2021/Abhinav.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

 Seed Contributor Workshop Dir for UUIC Hackillinois

---

remote/hackillinois-osf-2021/prateek.md

>
> /kind bug
> /kind design
> /kind flake
add prateek details
Fixes #
```release-note
NONE
```
```docs
DOCS
```

Add Prateek details file

---

remote/hackillinois-osf-2021/raul-higareda.md

>
> /kind bug
> /kind design
> /kind flake
Fixes # Thank you for the workshop!
```release-note
```
```docs
```

added file for Raul Higareda (worskhop attendee)

---

remote/hackillinois-osf-2021/dipto.md

>
> /kind bug
> /kind design
> /kind flake
Adds details about DIpto
Fixes #
```release-note
None
```
```docs
```

add details about Dipto

---

japan/ossj-2021/README.md

In this [PR](https://github.com/kubernetes-sigs/kubespray/pull/8284), oomichi became approver on kubespray repository.
This PR updates bio for oomichi.
NONE
NONE
```release-note
NONE
```
```docs
NONE
```
/assign @oomichi

Update oomichi's bio to approver on kubespray

---

japan/ossj-2021/workdir/shnmorimoto.md

training PR for ossj 2021 upstream training
Fixes #
```release-note
NONE
```
```docs
```
/sig node

add shnmorimoto.md for ossj 2021 upstream training

---

japan/ossj-2021/workdir/kujiraitakahiro-w664.md

Fixes #
```release-note
NONE
```
```docs
```

Add foo md kuji2(retry)

---

brazil/RicardoKatz.md

/kind cleanup
**What this PR does / why we need it**: Because @cpanato asked me to do so :)
Fixes #
```release-note
First PR from Ricardo
```
```docs
```

my first contrib PR

---

brazil/GeorgeTavares.md

/kind cleanup
Fixes #
```release-note
My First PR
```
```docs
```

My First Contrib

---

brazil/luizBernardo.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

my first contribution

---

brazil/mauricio-maia.md

First test contribution created during KCD Brazil
/kind cleanup
None
No
None

My first PR

---

brazil/WendellBorges.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

my first commit

---

brazil/leandroschwab.md

First test contribution created during KCD Brazil
/kind cleanup
None
No
None

My First PR!

---

brazil/WesleyDutra.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Wesley Dutra: My first PR

---

brazil/attendee-instructions.md

Fixes slack channels for Brazil

---

brazil/samylle-sales.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

add: my first pr

---

brazil/luisdknob.md

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**:  KCDBrasil Contributors Summit
Fixes #
```release-note
```
```docs
```

First PR - Luis Knob

---

brazil/JoseNeto.md

>
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Fixes #
```docs
```

First Commit - Kube (Neto)

---

brazil/learners-2022/knabben.md

This is the first PR for the remote workshop.
Fixes #
```release-note
NONE
```
```docs
```

Adding a new folders from workshop

---

australia/denstorti.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

Add Australia folder and greetings

---

japan/assets/attendee-prerequisites.md

This PR updates attendee prereuisites in japan folder.
It updates CLA sign procedule to use EasyCLA, because k8s community use EasyCLA as of now.
NONE
NONE
```release-note
NONE
```

Update prerequisites in japan folder

---

japan/OWNERS

>
> /kind bug
> /kind design
> /kind flake
Add ziyi-xie to japan OWNER as approvers
Fixes #
@atoato88 
```release-note
NONE
```
```docs
```

Add ziyi-xie to japan as approvers

---

japan/README.md

/kind cleanup
To use better word for future trainings.
```release-note
NONE
```

Fix Japan upstream training typo

---

japan/cndt-2022/README.md

/kind cleanup
oomichi's bio was old, so this update it.
There are two meanings on the above ;-)
```release-note
NONE
```

Update cndt-2022 profile

---

japan/cndt-2022/workdir/RenGoto.md

[Add] First commit!!
I want to try OSS contribution.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

[Add] First commit

---

japan/cndt-2022/workdir/eppppi.md

Add eppppi.md for cndt-2022 demo
Fixes #
```release-note
NONE
```
```docs
```
/sig testing

Add eppppi.md for cndt-2022 demo

---

japan/cndt-2022/workdir/soichiro-ueda.md

>
> /kind bug
> /kind design
> /kind flake
This PR adds soichiro-ueda.md. This is greeting from Soichiro Ueda.
Fixes #
```release-note
NONE
```
```docs
```

add soichiro-ueda.md for hands-on

---

japan/cndt-2022/workdir/yassan.md

Add yassan.md for CNDT2022 Upstream Training
Fixes #
```release-note
NONE
```
```docs
```

Add yassan.md for cndt2022 Upstream Training

---

japan/cndt-2022/workdir/mochizuki875.md

Add training file.
Fixes #
thx:)
```release-note
NONE
```
```docs
```

Add training file mochizuki875

---

japan/ood-2022/workdir/ryo-ma.md

Add ryo-ma.md
Fixes #
```release-note
NONE
```
```docs
```
/sig node

Add ryo-ma.md

---

japan/ood-2022/workdir/i-kenta.md

Add i-kenta.md for ood-2022 demo.
Fixes #
```release-note
None
```
```docs
```
/sig node

Add i-kenta.md for ood-2022 demo

---

japan/ood-2022/workdir/sathish-macro.md

Add sathish-macro.md for ood-2022 demo
Fixes #

commit doc file

---

japan/README.md

Fix typo
Fixes #
```release-note
NONE
```
```docs
```

Fix typo of README.md

---

japan/ood-2022/workdir/tomari-tatsuya.md

Add tomari-tatsuya.md
Fixes #
```release-note
NONE
```
```docs
```

Add tomari-tatsuya.md

---

remote/LEARNERS

Going through contributor workshop videos, and following the instructions to try out my first kubernetes development workflow.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

add frankyang-code4fun as remote learner

---

remote/LEARNERS

Just doing the `New Contributor Series` on youtube.
```release-note
NONE
```
```docs
```

add ggjulio to remote/LEARNERS

---

README.md

Sometimes self trainee submits PR that changes files in root directory. So this clarify where to practice submitting pull requests.
Fixes #
```release-note
NONE
```
```docs
```

Clarify where to practice submitting pull requests

---

india/remote/learners/Jaya.md
india/remote/learners/jayesh.md

>
kind api-change
> /kind bug
> /kind design
> /kind flake
Fixes #1067 
```
NONE
```
```docs
```

Updated jayesh.md

---

india/remote/learners/kumar.md

My first commit to Kubernetes

---

OWNERS

Ref: https://github.com/kubernetes/community/issues/7246
/assign @mrbobbytables

Add new contribex leads to OWNERS

---

remote/learners/ghakazian.md

>
> /kind bug
> /kind design
> /kind flake
Adding ghakazian as a learner
Fixes #
```release-note
NONE
```
```docs
```

Initial PR: Adding ghakazian to /remote/learners

---

remote/learners/molarom.md

Fixes #
```release-note
No
```
```docs
```

Initial PR: Add molarom to learners

---

remote/learners/its-kos.md

>
> /kind bug
> /kind design
/kind feature
> /kind flake
This PR adds my name to the remore/learners directory
Fixes #
NONE
My very first PR in the kubernetes space. Added my file to the learners directory as directed by the README
```release-note
NONE
```
```docs
```

Add myself to the learners directory

---

remote/learners/thomas.md

>
> /kind bug
> /kind design
> /kind flake
Just adding some notes for myself and others who may stumble upon it
Fixes #
Thanks for doing this ;)
```release-note
NONE
```
```docs
```

Add thomas.md to remote learners folder

---

japan/adhoc/workdir/tuibeovince.md

First commit PR
Fixes #
```release-note
NONE
```
```docs
```

Added tuibeovince.md file

---

japan/adhoc/workdir/ken-ajiro.md

Add a file for pull request test.
Add ken-ajiro.md into adhoc for PR testing.
Fixes #
```release-note
NONE
```
```docs
```

Add ken-ajiro.md

---

remote/OWNERS

>
> /kind bug
> /kind design
> /kind flake
Add ziyi-xie to remote OWNER as approvers
Fixes #
@shu-mutou 
Hi, I'm ziyi-xie currently working for the Japan area and really wish to work for the remote area. I'm wondering can I be one of the approvers in remote area as well?
```release-note
NONE
``` …

Add ziyi-xie to remote OWNERS

---

remote/learners/mash-China.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

My first  commmit  to resp

---

india/remote/learners/harshakp06.md

>
> /kind bug
> /kind design
> /kind flake
**Which issue(s) this PR fixes**: 
This PR is for verification of my GitHub account for the  contribution to Kubernetes project 
Fixes #
added the harshakp06.md file to the India/remote/learners folder
6 
This PR won't fix anything 
went with the slides/doc provided by the Kubernetes project for the sign of Contributor License Agreement (CLA) 
```release-note
```
**Additional …

Add harshakp06 to remote India learners

---

india/remote/learners/pankaj.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

added commit from india, my frist contribution to kubernetes

---

india/remote/learners/Saugata.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Playground contribution

---

remote/learners/yashwanth-mannem.md

This PR adds a new markdown file (yashwanth-mannem.md) to introduce myself, Yashwanth Mannem, to the Kubernetes community. The markdown file includes my background, goals, current work, and how I plan to contribute to the community.
None. This is an introductory PR.
This is my first PR to this community, and I'm looking forward to contributing more!
NONE
The markdown file serves as an introductory note for new community members to know more about me.

Introducing myself to the community

---

india/remote/learners/aayush.md

>
> /kind bug
> /kind design
> /kind flake
Fixes # First Commit
None
```release-note
None
```
```docs
```

contributor-playground first commit done !

---

remote/learners/vlasebian.md

>
> /kind bug
> /kind design
> /kind flake
Demo PR
Fixes #
Hi! Here's a dog:
```
__      _
o'')}____//
`_/      )
(_(_/-(_/
```
```release-note
NONE
```
```docs
```

demo contribution

---

remote/learners/LEARNERS
remote/learners/archer_chen.md

>
> /kind flake
add files cliams
2189
Fixes #
```release-note
NONE
```
```docs
```

have a good day!

---

remote/learners/LEARNERS

Fixes #
```release-note
NONE
```
```docs
```

test: my first pr

---

remote/learners/ii.md

>
> /kind bug
> /kind design
> /kind flake
Add ii.md (demo)
Fixes #
```release-note
NONE
```
```docs
```

pullrequset

---

remote/learners/msesto.md

Trying out working with forks.. thanks for this playground!
Fixes nothing
🪄 🎩 🐇 
```release-note
NONE
```
```docs
```

Adds msesto

---

remote/learners/alitari.md

>
> /kind bug
> /kind design
> /kind flake
testing
```release-note
NONE
```

feat(remote learners): add me

---

remote/learners/navodissa.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

K001-first-commit-to-kubernetes

---

remote/learners/ricardoapl.md

Practice submitting a Pull Request
None
None
```release-note
NONE
```
```docs
```

Add ricardoapl.md to remote learners

---

remote/learners/ysharma.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

First PR to kubernetes-sigs/contributor-playground

---

remote/learners/cameron.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

A pull request! Cool!

---

japan/OWNERS

/kind cleanup
This PR updates emeritus approvers in OWNERS at japan folder.
Some of current approvers graduated approver role in this folder, so we update the file.
Thank you for emeritus approvers.
NONE
NONE
```release-note
NONE
```
NONE

Update emeritus approvers in japan folder

---

japan/cncj-202403/README.md

This PR adds README.md file to cncj-202403 folder.
As of now, I'm cordinating facilitators, so I'll create other PR if all facilitators are fixed.
NONE
NONE
```release-note
NONE
```
NONE

Add README file to cncj-202403

---

japan/OWNERS

/kind feature
This PR add new members to OWNERS in japan folder.
They join our kubernetes upstream training as a facilitator.
NONE
NONE
```release-note
NONE
```
NONE

Add new members to OWNERS in japan folder

---

japan/cncj-202403/README.md

This PR updates the content in README.md:
- add text for CNCJ URL and description in Japanese
- add new facilitator
NONE
NONE
```release-note
NONE
```
NONE

Update README at cncj-202403

---

remote/learners/shiftyp.md

>
> /kind bug
> /kind design
> /kind flake
The personal purpose of this change is as follows:
- Learn the Kubernetes pull request process
- Practice a conformant commit message
- Sign the Contributor License Agreement
- Introduce myself to the Kubernetes Community
The general purpose of this change is as follows:
- Provide additional examples for future contributions
- Expand the contributor pool to the Kubernetes project
- Signal the importance of practice, research, and standards
- Reduce friction for …

Added learner markdown for user shiftyp

---

remote/learners/nielsreijers.md

Test PR to get to know the workflow and sign the CLA.
None
```release-note
NONE
```
```docs
```

Added learners/nielsreijers.md

---

remote/learners/agoel25.md

Test PR 
First PR in Kubernetes for CLA Signing

Test PR for CLA Signing

---

japan/cncj-202403/README.md

Add affiliations for facilitators of Kubernetes Upstream Training Japan by CNCJ 2024-03

Add affiliations

---

remote/learners/anveshjhuboo.md

>
> /kind bug
> /kind design
> /kind flake
Practice submitting PR for new contributor
Fixes #
```release-note
NONE
```
```docs
```

Add introduction for Anvesh to contribute to Kubernetes community

---

remote/learners/jesslane94.md

>
> /kind bug
> /kind design
> /kind flake
N/A
Fixes #
N/A
thx, just going thru the tutorial!
```release-note
NONE
```
```docs
```

added my readme

---

japan/cncj-202403/workdir/akiyama.md

>
add Akiyama.md into cncj-202403 for demo
Fixes #
NONE
```release-note
```
```docs
```

add Akiyama.md into cncj-202403 for demo

---

japan/cncj-202403/workdir/rei.md

>
add rei.md
Fixes #
```release-note
NONE
```
```docs
```

add rei.md

---

japan/cncj-202403/workdir/yuki.md

/kind design
Add yuki.md into cncj-202403
Fixes #
```release-note
NONE
```
```docs
```

Add yuki.md

---

japan/cncj-202403/workdir/foo_kzks.md

> 
add foo_kzks.md into cncj-202403 
Fixes #
```
None
```
```docs
```

add foo_kzks.md  into cncj-202403 

---

japan/cncj-202403/workdir/kaitok.md

>
Add `kaitok.md`
Fixes #
```release-note
NONE
```
```docs
```
/sig node
/sig testing

Add kaitok.md

---

japan/cncj-202403/kazuya.md

Add kazuya.md into cncj-202403 for demo
Fixes #
NONE
```release-note
```
```docs
```
/sig node
/sig testing

Add kazuya.md into cncj-202403 for demo

---

japan/cncj-202403/workdir/dkmats.md

Fixes #
```release-note
NONE
```
```docs
```

Add dkmats.md to cncj202403 for demo

---

japan/README.md

/kind cleanup
This PR removes the section for next schedule held in Japan.
NONE
NONE
```release-note
NONE
```
NONE

Remove the section for next schedule in Japan

---

japan/cncj-202403/workdir/shinji.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add shinji.md

---

remote/learners/Surajkumar98012.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

initial-commit

---

japan/adhoc/README.md

Update video list of Kubernetes Upstream Training for Japan
NONE
```release-note
NONE
```
```docs
NONE
```

Update video list for Japan

---

remote/learners/franzudev.md

Starting my contribution path on kubernetes

chore: first contribution

---

remote/learners/mbianchidev

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Create mbianchidev just to sign the CLA

---

remote/learners/ktvargo-ms.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

new learner in remote

---

remote/learners/rul

add remote/learners/rul to sign CLA

---

remote/learners/plusiv.md

Create remote/learners/plusiv.md to sign CLA

---

remote/learners/abhilekh41.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Create abhilekh41 just to sign the CLA

---

remote/learners/Tomlmmrs.md

First commit to sign the CLA
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Sign the CLA

---

remote/learners/tiffanylast.md

New contributor, first PR
None
Fixes #
Added tiffanylast.md to learners folder to create this pull request.
No.
```release-note
NONE
```
No

Create tiffanylast.md in learners folder to sign CLA

---

remote/learners/ducet8.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Create ducet8.md for CLA

---

remote/learners/skodkani.md
sample_sign_cla

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Added first commit.

---

remote/learners/harpreet9ja.md

First commit to sign the CLA
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Signing CLA

---

remote/learners/chen-keinan.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

chore: sign a cla

---

remote/learners/scaventz

Create scaventz just to sign the CLA

---

remote/learners/cvenigalla.md

>
> /kind bug
> /kind design
> /kind flake
PR to sign the CLA
Fixes #
PR to sign the CLA
```release-note
```
```docs
```

PR to sign the CLA

---

remote/learners/docandrew.md

>
> /kind bug
> /kind design
> /kind flake
PR for signing CLA
Fixes #
PR for signing the CLA
```release-note
NONE
```
```docs
```

PR for signing CLA

---

remote/learners/exklamationmark.md

Try signing CLA

---

remote/learners/aborrero.md

Commit to trigger CLA signing.
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

aborrero: CLA signing

---

remote/learners/csauoss.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

signing cla for csauoss

---

remote/learners/flmichel.md

Try to sign CLA

---

remote/learners/Maalvi14.md

Created Maalvi14.md to sign CLA.

PR to sign CLA

---

india/remote/learners/abhinovp

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Create abhinovp just to sign the CLA

---

remote/learners/pranavt84.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Signing the SLA

---

remote/learners/radvanszki.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Initial commit for signing CLA.

---

remote/learners/l0rd

Adding file to `remote/learners` to sign CLA

---

remote/learners/arseniizakharov.md

>
> /kind bug
> /kind design
> /kind flake
Create remote/learners/arseniizakharov.md to sign the CLA
NONE
NONE
```docs
```

Create arseniizakharov.md to sign the CLA

---

japan/adhoc/workdir/Okabe-Junya.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

[ja] sandbox for Japanese upstream training

---

japan/OWNERS

add @Okabe-Junya (myself) to Japanese OWNERS

Update Japanese OWNERS for upstream training

---

remote/learners/jlhello.md

> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: Create jhello.md to sign the CLA 
**Which issue(s) this PR fixes**: NONE
**Does this PR introduce a user-facing change?**: NONE
```
```

Create jlhello.md to sign CLA

---

OWNERS

I haven't had much in the way of time to respond to things that I get tagged on in this repo.
With that I'm going to go ahead and move myself to emeritus. :+1:

Move mrbobbytables to emeritus

---

japan/cncj-202408/README.md

/kind feature
- Initialize `japan/cncj-202408/` for [2024-08 k8s upstream training in Japan](https://community.cncf.io/events/details/cncf-cloud-native-community-japan-presents-cncj-kubernetes-upstream-training-japan-2024-08/)
Deploy preview: [link](https://github.com/kubernetes-sigs/contributor-playground/blob/32e50a8e079fbff3976772283635ac7ca12d3418/japan/cncj-202408/README.md)
/cc shu-mutou atoato88

[ja] Initialize 2024-08 k8s upstream training in Japan

---

remote/learners/sasanbabai.md

Try to sign the CLA

---

remote/learners/Sudomarko.md

Sudomarko sign CLA

---

remote/learners/letajmal.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

letajmal sign CLA

---

remote/learners/rezkam.md

Sample to PR to sign the CLA for rezkam
Fixes #
```release-note
```
```docs
```

Create rezkam.md to sign the CLA

---

remote/learners/travisyx.md

>
> /kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**
This PR adds travisyx.md to remote/learners to sign the CLA.
```release-note
```

Add travisyx.md to remote/learners

---

remote/learners/shumakriss.md

Github user Shumakriss ready to sign CLA

---

README.md

Many PRs are not being submitted to the proper directory. They are either mistaking past KCWs for areas or are submitted to inactive event directories, so rewrite the description to clarify.
Fixes #
```release-note
NONE
```
```docs
```

Clarify the submit target for PR

---

japan/assets/attendee-prerequisites.md

update not found link in japan/attendee-prerequisties
None
None

update link to code-of-conduct in japan attendee prerequisites

---

japan/assets/attendee-prerequisites.md

add a missed word in japan/attendee-prerequisites.md
NONE
NONE
```docs
```

doc: add missed word in japan/attendee-prerequisites.md

---

remote/learners/kvifern.md

Create kvifern.md to sign the CLA

---

remote/learners/sadasu.md

>
PR to sign the CLA for sadasu
Fixes #
```release-note
```
```docs
```

Signing the K8s CLA

---

remote/learners/wallee94.md

Following the contributors guide. This is a sample PR to sign the CLA

Create wallee94 to sign the CLA

---

remote/learners/andreidon.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

 Added andreidon.md to remote/learners folder

---

remote/learners/sshambar.md

Add sshambar.md to remote/learners folder

---

remote/learners/martinkunc

Create martinkunc just to sign the CLA

---

remote/learners/mashasht.md

Adding a new contributor, signing the CLA

Add new contributor mashasht.

---

remote/learners/saiaunghlyanhtet.md

>
> /kind bug
> /kind design
/kind feature
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

sign cla by saiaunghlyanhtet

---

remote/learners/hcc429.md

create hcc429 to sign the CLA

---

remote/learners/RamBITS-AI

Create RamBITS-AI just to sign the CLA

---

remote/learners/souheilbenslama.md

Uncomment only one  /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:
Add souheilbenslama.md
Fixes #
NONE

add souheilbenslama as a learner

---

remote/learners/walt.md

>
/kind bug
> /kind design
> /kind flake
add `walt.md` file
None
None
```release-note
NONE
```
```docs
```

added walt.md to remote/learners folder

---

remote/learners/alessandrofazio.md

add alessandrofazio.md to remote/learners folder
Fixes #
```release-note
NONE
```
```docs
```

add alessandrofazio.md to remote/learners folder

---

remote/learners/petahhh.md

Adds petahhh.md to remote/learners directory for signing the CLA
N/A
```release-note
NONE
```
```docs
```

add petahhh.md to remote/leaners

---

remote/learners/CefBoud

add CefBoud.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add CefBoud.md toremote/learners dir

---

remote/learners/ish.md

>
**What this PR does / why we need it**: Adding  `remote/learners/ish.md` to sign CLA.
**Which issue(s) this PR fixes**: None
**Special notes for your reviewer**: None
```release-note
NONE
```
```docs
```

add ish.md to sign the CLA

---

remote/learners/kingbj940429.md

>
Add kingbj940429.md into learner
Fixes #
```release-note
None
```
```docs
```

Add kingbj940429 as a learner

---

remote/learners/zedawg.md

>
> /kind bug
> /kind design
> /kind flake
add remote/learners/zedawg.md
Fixes #
```release-note
```
```docs
```

add remote/learners/zedawg.md for sign cla

---

japan/adhoc/workdir/osatest.md

Add osatest.md into adhoc
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

Add osatest.md into adhoc

---

remote/learners/russellcain.md

add russellcain.md to remote/learners folder to join the community (adding feature to KubeVirt).
None
None
None

add russellcain.md to remote/learners folder

---

remote/learners/anurag252.md

>
> /kind bug
> /kind design
> /kind flake
To enable anurag252 to sign CLA
Fixes #
```release-note
```
```docs
```

chore: add anurag252.md to remote/learners folder

---

remote/learners/yongruilin.md

>
> /kind bug
> /kind design
> /kind flake
Add yongruilin.md to remote learner dir
Fixes #
```release-note
NONE
```
```docs
```

add yongruilin to remote learner dir

---

remote/learners/raghu.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add raghuramlavan to remote. First PR

---

remote/learners/rogvc.md

Adds @rogvc as a contributor
N/A
```release-note
NONE
```
```docs
```

Adds rogvc as a contributor

---

remote/learners/mateo.md

add mateo762.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add mateo.md to remote/learners folder

---

remote/learners/ebouvard.md

Add ebouvard.md to remote/learners to sign CLA
```release-note
NONE
```
```docs
```

add ebouvard to sign CLA

---

remote/learners/alexanderstephan.md

Just a dummy PR for adding CLA.
Fixes #
```release-note
NONE
```
```docs
```

Add alexanderstephan.md to sign CLA

---

remote/OWNERS

>
> /kind bug
> /kind design
> /kind flake
Add nasa9084 to remote OWNER as approvers
Fixes #
```release-note
NONE
```
```docs
```

Add nasa9084 to remote OWNERS

---

remote/learners/nicobistolfi.md

Add nicobistolfi.md to remote/learners folder for practicing PR submission
Fixes #
```release-note
NONE
```
```docs
```

Create `remote/learners/nicobistolfi.md 

---

remote/learners/devemilio96.md

add devemilio96.md to remote/learners folder for practicing PR submission.
Fixes #
```html
NONE
```
```html
```

add devemilio96.md to remote/learners folder

---

remote/learners/sonu1311.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add sonu1311.md to remote/learners folder

---

remote/learners/coderocker.md

This PR adds `remote/learners/coderocker.md` as part of the CLA signing process and my first PR contribution. It follows the guidelines for making the first PR.
Fixes #N/A
This is my first PR to the repo, excited to contribute and be part of the Kubernetes community!
```release-note
NONE
```
```docs
N/A
```

Add remote/learners/coderocker.md for CLA signing purposes

---

remote/learners/ebblake.md

>
> /kind bug
> /kind design
> /kind flake
add remote/learners/ebblake.md to trigger CLA signing process
Fixes #
```release-note
NONE
```
```docs
```

Add remote/learners/ebblake.md for CLA signing purposes

---

remote/learners/shakthi.md

>
> /kind bug
> /kind design
kind documentation
> /kind flake
What this PR does / why we need it**:
add shakthi.md to remote/learners folder for practicing PR submission.
Fixes #
Does this PR introduce a user-facing change?**: 
None
```release-note
```
```docs
```

add shakthi.md to remote learners

---

brazil/YannKistenmacker.md

>
> /kind bug
> /kind design
/kind failing-test
> /kind flake
add yannkistenmacker.md to brazil folder for practicing PR submission.
Fixes #
None
```release-note
```
```docs
```

add yannkistenmacker.md to brazil folder

---

remote/learners/antonio.md

Add antonio.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Make antonio a Kubernetes contributor 🙋‍♂️

---

remote/learners/siddharth.md

Adding packetsnscripts.md to remote/learners for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Make packetsnscripts a Kubernetes contributor

---

remote/learners/ganga.md

gangahiremath starts contribution in kubernetes community

---

remote/learners/fan.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

Add remote/learners/fan.md

---

remote/learners/sumanjeet.md

add sumanjeet.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add sumanjeet.md to remote/learners folder

---

remote/learners/hoony9x.md

First commit & practice for how to write PR into Kubernetes projects.
Nothing
```release-note
NONE
```
```docs
```

Add `hoony9x.md` to `remote/learners`

---

remote/learners/x-color.md

To sign CLA
Fixes #
```release-note
NONE
```
```docs
```

x-color starts contribution in the Kubernetes community

---

remote/learners/gsstuart.md

>
> /kind bug
> /kind design
> /kind flake
signing CLA
Fixes #
```release-note
```
```docs
```

add gsstuart.md to remote/learners folder`.

---

remote/learners/Praduman.md

Fixes #
```release-note
NONE
```
```docs
```

added praduman.md

---

remote/learners/meowlvaro.md

>
> /kind bug
> /kind design
> /kind flake
Add `meowlvaro.md` to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Add meowlvaro.md for practicing PR submissions

---

remote/learners/henrykhosasih.md

add henrykhosasih.md to learners

---

remote/learners/emc2016.md

>
> /kind bug
> /kind design
> /kind flake
Sign SLA
Fixes #
```release-note
```
```docs
```

Add emc2016.md to remote/learners folder

---

remote/learners/troll-os.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Added myself as a learner to sign CLA

---

remote/learners/vishuvenu.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add vishuvenu to remote. First PR

---

remote/learners/chamarsh.md

>
> /kind bug
> /kind design
> /kind flake
Add Chamarsh.md to remote/learners
Fixes #
```release-note
```
```docs
```

Add chamarsh.md to remote/learners

---

remote/learners/kit_hung.md

add kit_hung.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add kit_hung.md

---

remote/learners/tarunsunny3.md

Fixes #
```
NONE
```
```docs
```

Add tarunsunny3.md file

---

austria/awgrass.md

Practice creating first MR
Fixes #
```release-note
```
```docs
```

add austria folder + md file

---

brazil/moreirayokoyama.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add moreirayokoyama.md

---

remote/learners/root30.md

Add remote/learners/root30.md for practicing PR submisison
Fixes #
```release-note
```
```docs
```

Add remote/learners/root30.md

---

remote/learners/sumitgarg44.md

Add sumitgarg44.md in remote/learners directory for practicing PR submission and acceptance of CLA.
None

Add sumitgarg44.md in remote/learners directory.

---

remote/learners/hausertt.md

add hausertt.md to remote/learners folder for signing the cla.
Fixes #
```release-note
NONE
```
```docs
```

Add hausertt.md to remote/learners folder

---

remote/learners/anilg.md

add anilg.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
```
```docs
```

add anilg.md to remote/learners folder

---

remote/learners/duckhue01.md

Add vietnam/DK.md
Fixes #
```release-note
NONE
```
```docs
```

feat: add duckhue01.md

---

remote/learners/mokaz111.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
sign the cla
```

Mokaz111 patch 1

---

remote/learners/seitarof.md

add seitarof.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Add seitarof.md to remote/learners folder

---

remote/learners/wanglx.md

add wanglx.md to remote/learners folder for practicing PR submission.
Fixes #
None
```release-note
NONE
```
```docs
```

Add wanglx.md to remote/learners

---

japan/OWNERS

>
> /kind bug
> /kind design
> /kind flake
add inductor to Japanese OWNERS
Fixes #
```release-note
```
```docs
```

Add inductor to japan OWNER as approver

---

japan/cndw-2024/README.md

Added Kohei Ota as a facilitator and updated Roles for some facilitator.
Fixes #
@Okabe-Junya
```release-note
NONE
```
```docs
```

Update Facilitators for japan/cncw-2024

---

remote/learners/cdacosta.md
remote/learners/cody.md

Signing CLA for contributor purposes.
N/A
Fixes #
N/A
None
None

Adding md with CLA included

---

remote/learners/obamwonyi.md

added obamwonyi.md to the remote/learners directory, for practicing contributing to Kubernetes.
Fixes #
New Contributor
```release-note
NONE
```
```docs
```

added obamwonyi.md to remote/learners directory

---

remote/learners/FarmerChillax.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

docs: add test pr

---

japan/cndw-2024/workdir/eddyariki.md

>
Adds eddyariki.md into cndw-2024.
Fixes #
```release-note
NONE
```
```docs
```

Adds eddyariki.md into cndw-2024

---

japan/cndw-2024/workdir/na2na.md

>
Add na2na.md into cndw-2024
Fixes #
```release-note
```
```docs
```

Add na2na.md into cndw-2024

---

japan/cndw-2024/workdir/jkjk.md

>
Add jkjk.md into cndw-2024
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

Add jkjk.md into cndw-2024

---

japan/cndw-2024/workdir/rainier.md

Add rainier.md in cndw-2024
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

Add rainier.md in cndw-2024

---

japan/cndw-2024/workdir/iwanaga.md

Add iwanaga.md into cndw-2024
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

Add iwanaga.md

---

japan/cndw-2024/workdir/t-katsumura.md

>
Add t-katsumura.md into japan/cndw-2024/workdir/
Fixes #
```release-note
```
```docs
```
/sig testing
/sig docs

Add t-katsumura.md into japan/cndw-2024/workdir/

---

japan/cndw-2024/workdir/oirom.md

>
Add oirom.md into cndw-2024
Fixes #
```release-note
NONE
```
```docs
```
/sig docs

Add oirom.md into cndw-2024

---

japan/cndw-2024/workdir/sogawa.md

>
Add sogawa.md to cndw-2024
Fixes #
```release-note
NONE
```
```docs
```

Add sogawa.md

---

japan/cndw-2024/workdir/yi-ymmt.md

Add yi-ymmt.md into cndw-2024
Fixes #
```release-note
NONE
```
```docs
```
/sig docs

Add yi-ymmt.md into cndw-2024

---

japan/cndw-2024/workdir/yuto-kimura-g.md

Hands on: Add yuto-kimura-g.md into cndw-2024
Fixes #
```release-note
```
```docs
```

Add yuto-kimura-g.md into cndw-2024

---

japan/cndw-2024/workdir/358.md

Add 358.md into CNCW2024
Fixes #
```release-note
```
```docs
```
/sig testing
/sig docs

Add 358.md into CNCW2024

---

japan/cndw-2024/workdir/tomohiro.md

/sig documentation
/kind test
/kind docs

Add tomohiro.md

---

remote/learners/sitzmaa.md

Added sitzmaa.md to remote/learners to practice first PR submission
Fixes #
```release-note
NONE
```
```docs
```

Created sitzmaa.md in remote/learners

---

remote/learners/koti.md

>
> /kind bug
> /kind design
kind documentation
> /kind flake
This PR I submitted to sign CLA and for making my very first contribution to k8s via Code.
Fixes #
```release-note
```
NONE
```docs
```

Koti's first PR

---

remote/learners/troychiu.md

This PR is submitted to sign the Contributor License Agreement (CLA)
Fixes #N/A 
```release-note
NONE
```
```docs
```

Add first PR for CLA signing

---

remote/learners/tomdemay.md

>
/kind bug
> /kind design
> /kind flake
**What this PR does / why we need it**: add tomdemay.md to remote/learners folder so I can fix a bug in manifest files for the guestbook example. 
Fixes #
**Does this PR introduce a user-facing change?**: I believe so. Developers are unable to deploy the guestbook example because gb-frontend image has been upgrade to v5. The version specified in the manifests (v4) is no longer available. 
```release-note
Upgrading …
```

Add remote/learners/tomdemay.md

---

remote/learners/desirefreer.md

add desirefreer.md to remote/learners folder for practicing PR submission.
Fixes #

Add desirefreer.md to remote/learners

---

remote/learners/madong.md

>
> /kind bug
> /kind design
> /kind flake
Add madong.md
Fixes #
```release-note
```
```docs
```

Add madong.md

---

remote/learners/bf0916.md

Pull Request to Sign CLA
add bf0916.md for signing the CLA
Fixes #
```release-note
None
```
```release-note
None
```
```release-note
None
```
```docs
N/A
```

add bf0916.md to remote/learners folder

---

remote/learners/xirehat.md

add xirehat.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Add xirehat.md

---

remote/learners/mahdibouaziz.md

Add mahdibouaziz.md to remote/learners folder in order to sign the CLA
Fixes #
```release-note
NONE
```
```docs
```

add mahdibouaziz.md to remote/learners folder 

---

remote/learners/noahwicz.md

>
> /kind bug
> /kind design
> /kind flake
added noahwicz.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Added noahwicz.md to the remote/learners directory for practicing PR submission

---

remote/learners/anant_raj.md

add anant_raj.md to remote/learners folder to practice first PR
Fixes #
```release-note
NONE
```
```docs
```

add anant_raj.md to remote/learners folder

---

remote/learners/linde.md

enables me to later contribute
Fixes # n/a

adding a new contributor 

---

remote/learners/Sakshich001.md

This PR is submitted to sign the Contributor License Agreement (CLA)
Fixes #N/A
```
NONE
```

Add my first PR for CLA signing 

---

remote/learners/omkar_nag.md

This PR demonstrates a simple contribution to the Kubernetes contribution-playground repository.
NONE
This is my first contribution to the Kubernetes ecosystem, and feedback is welcome for my further contributions.
```release-note
NONE

First PR + Signing CLA

---

remote/learners/simonfogliato.md

>
> /kind bug
> /kind design
> /kind flake
Added simonfogliato.md in remote/learners.
Fixes #
```release-note
```
```docs
```

Added simonfogliato.md in remote/learners.

---

remote/learners/rbaturov.md

add rbaturov.md to remote/learners folder for practicing PR submission.
None
```release-note
```
```docs
```

add rbaturov.md to remote/learners folder

---

remote/learners/jiahuipaung.md

This PR demonstrates a simple contribution to the Kubernetes contribution-playground repository.
NONE
This is my first contribution to the Kubernetes ecosystem, and feedback is welcome for my further contributions.
```release-note
NONE
```
```docs
NONE
```

First PR and Signing CLA

---

remote/learners/talnetd.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

[added] my 1st contrib to test PR

---

remote/learners/yverma.md

add yverma.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
None
```
```docs
```

 add yverma.md to remote/learners folder

---

remote/learners/saf1u.md

add saf1u.md to remote/learners folder for practicing PR submission.
Fixes #
```
NONE
```
```
```

add saf1u to learners

---

remote/learners/seagyn.md

add seagyn.ms to remote/learners folder
Fixes #
```release-note
NONE
```
```docs
```

add seagyn.ms to remote/learners folder

---

remote/learners/miseratio.md

Add miseratio.md to the remote/learners directory for practicing PR submission and to sign the CLA
Fixes #
```release-note
NONE
```
```docs
```

Create miseratio.md / signing CLA

---

remote/learners/attyxy.md

Sign CLA
Fixes #
```release-note
NONE
```
```docs
```

Add remote/learners/attyxy.md

---

remote/learners/GarrickHe.md

Add GarrickHe.md to the remote/learners directory for practicing PR submission and to sign the CLA
Fixes #
```
NONE
```
```
```

Add GarrickHe.md to remote/learners

---

remote/learners/mochivi.md

Add remote/learners/mochivi.md for my first PR, learning to contribute
Fixes #
```release-note
NONE
```
```docs
```

add remote/learners/mochivi.md

---

remote/learners/yanai.md

Add yanai_2nd md

---

remote/learners/wieczorekpatryk.md

This allows me to practice the PR
Fixes #
```release-note
```
```docs
```

Joining-k8s-opensource

---

remote/learners/mpelekh.md

Followed the steps in https://github.com/kubernetes/community/tree/master/contributors/guide#sign-the-cla
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

add mpelekh.md to remote/learners folder

---

remote/learners/eliesercla

Fixes None
want to sign the CLA
```release-note
no
```
```docs
no
```

add eliesercla to remote/learners folder

---

remote/learners/arel.md

Adding `arel.md` file to sign CLA to be able to contribute
Fixes #
```release-note
NONE
```
```docs
```

add arel.md to remote/learners folder.

---

remote/learners/yurizf.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

yurizf CLA signing

---

remote/learners/mridha.md

>
for me to practice PR creation in k8s repo and part of my CLA signing process
Fixes #
```release-note
NONE
```
```docs
```

docs: add mridha.md to remote/learners folder

---

remote/learners/prashant231203.md

**What type of PR is this?**  
> /kind documentation  
**What this PR does / why we need it:**  
This is my first contribution to the Kubernetes Contribution Playground to practice the CLA signing process. This PR is for learning purposes and does not introduce any functional changes.  
**Which issue(s) this PR fixes:**  
N/A  
**Special notes for your reviewer:**  
This PR is only for practice and verification of the CLA process.  
**Does this PR introduce a user-facing change?**  
```release-note
NONE

Title: My First Contribution – CLA Practice

---

remote/learners/paschalis.md

Sign the CLA as per https://github.com/kubernetes/community/tree/master/contributors/guide#sign-the-cla
Fixes #
```release-note
NONE
```
```docs
```

add paschalis.md to remote/learners folder

---

remote/learners/chaitushiva.md

This is my first contribution to the Kubernetes Contribution Playground to practice the CLA signing process. This PR is for learning purposes and does not introduce any functional changes.
N/A
This PR is only for practice and verification of the CLA process.
Does this PR introduce a user-facing change?
NONE

PR to contribute 

---

brazil/gaedrumond.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

new brazilian contributor

---

remote/learners/jaredDlewis.md

> /kind bug
> /kind design
> /kind flake
Add jaredDlewis.md to remote/learners folder for practicing PR submission and to sign CLA.
Fixes #
```release-note
NONE
```
```docs
```

add jaredDlewis.md to remote/learners folder

---

remote/learners/ta8i2chi8.md

add ta8i2chi8.md to remote/learners folder.
Fixes #
```release-note
NONE
```
```docs
```

add ta8i2chi8.md to remote/learners folder

---

remote/learners/sibo-t.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
NONE
```

add sibo-t to remote/learners

---

remote/learners/cyrilcsr.md

add cyrilcsr.md to remote/learners to sign CLA
Fixes #
```release-note
NONE
```
```docs
```

add cyrilcsr.md to remote/learners

---

remote/learners/henricj.md

>
> /kind bug
> /kind design
> /kind flake
add henricj.md to remote/learners
Fixes #
```release-note
NONE
```
```docs
```

Add henricj.md to remote/learners

---

remote/learners/khanhkhuat1504.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

add khanhkhuat1504.md to remote/learners folder

---

remote/learners/zechariahks.md

Add zechariahks.md to remote/learners folder for start contributing to k8s projects.
Fixes #
```release-note
NONE
```
```docs
```

Add zechariahks.md to remote/learners folder

---

remote/learners/xxcc.md

**What this PR does / why we need it:**
Add zechariahks.md to remote/learners folder for start contributing to k8s projects.
**Which issue(s) this PR fixes:**
Fixes #
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
`NONE`
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
`NONE`

Add xxcc.md to remote/learners folder

---

remote/learners/vandathron.md

Following contribution guideline to practice PR submissions and start contributing to k8s.
```
NONE
```
Fixes #
```
NONE
```
```
NO
```
```docs
```

add vandathron.md to remote learners

---

remote/learners/samir634.md

>
> /kind bug
> /kind design
> 
> /kind flake
add samir634.md to remote/learners folder for practicing PR submission
Fixes #
```release-note
NONE
```
```docs
```

adding samir634 to remote/learners

---

remote/learners/deepanshukumar.md

Add hajiler.md to remote/learners for PR submission practice.
Fixes #
NONE

Introductory commit

---

remote/learners/sourabhdeshmukh.md

Add sourabhdeshmukh.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
None
```
```docs
```

Add sourabhdeshmukh.md to remote/learners folder

---

remote/learners/hajiler.md

Add hajiler.md to remote/learners for PR submission practice. 
Fixes #
```release-note
NONE
```
```docs
```

Introduction commit

---

remote/learners/ryantbvt.md

Add ryantbvt.md to remote/learners to sign CLA + practice PR submission
Fixes #
```
NONE
```
```
NONE
```

add ryantbvt.md to remote/learners folder

---

remote/learners/mrCR100.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

a new Shanghai contributor

---

remote/learners/tomma-a.md

practicing PR submission and trigger CLA sign
Fixes #
```
None
```
```docs
```

tomma-a CLA sign

---

remote/learners/koobfoo.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Contributor playground commit for koobfoo.

---

remote/learners/eramoto.md

Add eramoto.md to confirm my CLA

---

remote/learners/satyxm.md

add satyxm.md to remote/learners folder for practicing PR submission.
Fixes #
```
NONE
```
```docs
```

add satyxm.md to remote/learners folder

---

remote/learners/kfess.md

add kfess.md to remote/learners folder to sign CLA.
Fixes #
NONE

chore: add kfess.md to sign CLA

---

remote/learners/pfeifferj.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

dummy commit pfeifferj

---

remote/learners/svelama.md

adds svelama.md to remote/learners folder for practicing PR submission.
**Which issue(s) this PR fixes:**
Fixes #
```release-note
None
```
```docs
```

add svelama.md to remote/learners folder

---

remote/learners/snambi.md

k8s CLA
>
Fixes #
**Special notes for your reviewer**: CLA
```release-note
No
```
```docs
No
```

PR for signing CLA 

---

remote/learners/radoslawc.md

add radoslawc.md to remote/learners folder to sign CLA + practice PR submission
Fixes #
```release-note
```
```docs
```

adding radoslawc.md

---

remote/learners/gawbul.md

>
> /kind bug
> /kind design
> /kind flake
This adds a gawbul.md file to the remote learners folder. This is to practice submitting a contribution to the project. It also allows me to sign the Contributor License Agreement.
Fixes #
```release-note
NONE
```
```docs
```

Add gawbul to remote learners

---

remote/learners/brunogomes011.md

>
> /kind bug
> /kind design
> /kind flake
add brunogomes011.md to remote/learners folder to become one k8s contributor
Fixes #
```release-note
NONE
```
```docs
```

add brunogomes011.md to remote/learners folder

---

remote/learners/iropz.md

add iropz.md to remote/learners folder for practicing PR submission.
Fixes #
```
NONE
```
```
```

add iropz.md to remote/learners folder

---

remote/learners/edax97.md

Signing the CLA
>
> /kind bug
> /kind design
> /kind flake
Adding myself to remote/learners
Fixes #
```release-note
```
```docs
```

Add Edax97 to remote/learners

---

remote/learners/calebandria.md

Greetings!
I want to contribute to code in k8s. I have already signed the CLA.
Would you please accept my request to be a part of the project ? 
Kind regards,
Tiana Kaleba Andriamanaja

my first contribution to k8s

---

remote/learners/leulmes.md

add ziyi.md to remote/learners folder for practicing PR submission.
Fixes #
NONE

Add leulmes.md to remote/learners folder

---

remote/learners/mocz.md

add mocz.md to remote/learners folder for practicing PR submission.
Fixes #
```
NONE
```
```docs
```

add mocz.md to remote/learners folder

---

remote/learners/limbaniharsh.md

add limbaniharsh.md to remote/learners for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Create limbaniharsh.md for CLA

---

remote/learners/teaglebuilt.md

add `teaglebuilt.md` to `remote/learners` for CLA signing up
Fixes #
NONE

creating teaglebuilt.md in remote learners

---

remote/learners/u-kai.md

add u-kai.md to remote/learners for CLA signing up
Fixes #
```release-note
```
NONE
```docs
```

add u-kai.md to remote/learners folder

---

remote/learners/gdromanov.md

Adds gdromano.md to the remote/learners directory for practicing PR submission.
Fixes #
Have a great day! :sparkles:
```release-note
NONE
```
```docs
```

add remote/learners/gdromanov.md

---

remote/learners/rltrancodex.md

Adds rltrancodex.md to the remote/learners directory for practicing PR submission.
N/A
Have a great day! ✨
```
NONE
```
```
```

add rltrancodex.md to remote/learners for CLA signing

---

remote/learners/ronaldngounou.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add ronaldngounou.md to remote/learners

---

remote/learners/akhil.md

Initial PR for signing CLA
None
Fixes #
Help me onboard K8s contributors community.
None
```release-note
```
```docs
```

Initial PR from akhiljain23 for signing CLA

---

remote/learners/danielkimb.md

add danielkimb.md to remote/learners folder for practicing PR submission.
Fixes #
NONE

feat: Add danielkimb.md

---

remote/learners/y-isono.md

**What this PR does / why we need it:**
add y-isono.md to remote/learners folder for practicing PR submission.
Fixes #
```
NONE
```
```

add y-isono.md to remote/learners folder

---

remote/learners/harshit77.md

add harshit77.md to remote/learners folder for practicing PR submission.
Fixes #
```
NONE
```
```
```

add harshit77.md to remote/learners folder 

---

remote/learners/nikeshmaharja.md

"Start small, stay consistent, and automate early."
>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Starting small !! more to go ワクワク

---

remote/learners/Ogu1208.md

add ogu1208.md to remote/learners folder for practicing PR submission and CLA signing.
Fixes #
```release-note
NONE
```
```docs
```

add ogu1208.md to remote/learners folder for CLA Signing

---

remote/learners/ramasurendra.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

0th PR more to go........ !! Jai Shri Ram !!

---

remote/learners/Rohit-wagh.md

Complete CLA signing for future contributions

---

czechia/OWNERS
czechia/prague/README.md

>
> /kind bug
> /kind design
> /kind flake
This PR adds czechia folder to contributor-playground's master branch
Fixes #1773
Hello!
```release-note
NONE
```
```docs
```

Merge feature/hello-world to master #1773

---

remote/learners/drlatt.md

add drlatt.md to remote/learners folder for practising PR submission
Fixes #
```release-note
NONE
```
```docs
```

add drlatt.md to remote/learners folder

---

india/remote/learners/navinkumar.md

add navinkumar.md to /india/remote/learners/navinkumar.md folder for practicing PR submission.
Fixes #
NONE

commit for CLA

---

remote/learners/georgehyde-dot.md

add georgehyde-dot.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
```
```docs
```

add georgehyde-dot.md to remote/learners folder

---

india/remote/learners/itspacchu.md

add itspacchu.md to remote/learners folder for practicing PR submission.
Fixes #
> NONE
> NONE

Add itspacchu.md for CLA signing

---

remote/learners/bryagd.md

>
> /kind bug
> /kind design
> /kind flake
CLA SIGN
Fixes #
```release-note
None
```
```docs
```

add bryagd.md to remote/learners folder for CLA Signing

---

remote/learners/jonataswingeter.md

**What this PR does / why we need it:**
add jonataswingeter.md to remote/learners folder for practicing PR submission.
**Which issue(s) this PR fixes:**
Fixes #
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
```release-note
NONE
```
```docs
```

CLA assignment

---

remote/learners/arunjunai.md

**What this PR does / why we need it**: 
add arunjunai.md to remote/learners folder for practicing PR submission
Fixes # 
```release-note
NONE
```
```docs
```

add arunjunai.md to remote/learners folder

---

remote/learners/vg.md

add vg.md to remote/learners folder for practicing PR submission.
Fixes #

Add vg.md to remote/learners folder

---

remote/learners/misterderpie.md

add misterderpie.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add misterderpie.md to remote/learners folder

---

remote/learners/bupd.md

The purpose of this PR to practice PR submission and CLA signing.
Fixes #
```release-note
NONE
```
```docs
```

Add bupd.md to remote/learners

---

remote/learners/suyash-811.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Adds new learner to remote/learners

---

remote/learners/umbertocicciaa.md

add umbertocicciaa.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add umbertocicciaa.md to remote/learners folde

---

remote/learners/dylanzenner.md

add dylanzenner.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Add dylanzenner.md into /remote/learners/ folder

---

remote/learners/tomwang57.md

Add `tomwang57.md` to `remote/learner` folder to sign CLA and practice PR submission
Fixes #
```release-note
NONE
```
```docs
```

add tomwang57.md to remote/learners folder

---

remote/learners/davidbaena.md

Fixes #
```release-note
NONE
```
```docs
```

Update davidbaena.md remote entry

---

remote/learners/cbbond.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add cbbond to remote/learners

---

remote/learners/rsingh0101.txt

This is a practice PR to sign the Kubernetes CLA and test the contributor workflow.
None
This is part of the first-time contributor process.
```release-note
NONE
```
```docs
NONE
```

Added rsingh0101 to remote/learners

---

japan/cnds-2025/workdir/sera.md

add sera.md into cnds-2025
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

add sera.md into cnds-2025

---

japan/cnds-2025/workdir/tmurakam.md

Add tmurakam.md to cnds-2025
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

add tmurakam.md to japan/cnds-2025/workdir

---

japan/cnds-2025/workdir/wa6sn.md

>
Add wa6sn.md into CNDS2025
Fixes #
```release-note
```
```docs
```
/sig testing
/sig docs

Add wa6sn.md into CNDS2025

---

japan/cnds-2025/workdir/kitsuyaazuma.md

>
This PR adds `kitsuyaazuma.md` to cnds-2025.
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

Add kitsuyaazuma.md

---

japan/cnds-2025/workdir/sanghyuklee.md

Add 1 document for contribute practice
Fixes #
NONE
```release-note
NONE
```
```docs
```

Add sanghyuklee.md into japan/cnds-2025

---

japan/cnds-2025/workdir/r-hnf.md

add r-hnf.md into cnds-2025
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

add r-hnf.md into cnds-2025

---

japan/cnds-2025/workdir/kurita.md

Add kurita.md into japan/cnds-2025/workdir
Fixes #
```release-note
NONE
```
```docs
```
/sig testing
/sig docs

Add kurita.md into japan/cnds-2025/workdir

---

japan/cnds-2025/workdir/kurosu.md

>
Add kurosu.md
Fixes #
```release-note
NONE
```
```docs
```

Add kurosu.md

---

japan/cnds-2025/workdir/hiroshi.md

>
Add hiroshi.md
Fixes #
```release-note
None
```
```docs
```
/sig testing
/sig docs

Add hiroshi.md

---

japan/cnds-2025/workdir/saito.md

add saito.md

---

remote/learners/d0w.md

Adds d0w.md to remote/learners folder to practice PR 
Fixes #
```release-note
NONE
```
```docs
```

Add d0w.md to remote/learners folder

---

remote/learners/condaatje.org

approval process
(redline: condaatje contributions cannot be included in closed source versions of k8s in the future, merging this PR constitutes acceptance)
```release-note
NONE
```
```docs
```

add condaatje

---

remote/learners/gk16.md

add gk16.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Add gk16.md to remote/learners folder

---

remote/learners/yaruyng.md

add yaruyng's learn.md
Fixes #
no
```release-note
NONE
```
```docs
```

feat: add yaruyng's learn.md

---

remote/learners/yujen77300.md

CLA check 
add yujen77300.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
```
```docs
```

add file for CLA

---

remote/learners/aletundo.md

>
> /kind bug
> /kind design
> /kind flake
NONE
```release-note
NONE
```
```docs
```

Create aletundo.md to sign CLA and start contributing

---

remote/learners/MattIvan.md

add MattIvan.md to remote/learners folder for onboarding. 
Fixes #
```release-note
NONE
```
```docs
```

add MattIvan.md to remote/learners folder

---

india/remote/learners/pawaspy.md

add pawaspy.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Add my username to contributor playground

---

remote/learners/jmathews1.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

added jmathews1.md file

---

austria/clasign.md

The purpose of this PR to practice PR submission and CLA signing.
Fixes #
```release-note
NONE
```
```docs
```

PR for entlein to sign the CLA

---

japan/OWNERS

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```
/cc @sreeram-venkitesh

Add sreeram-venkitesh (for tmp use)

---

japan/japan-community-day-2025/workdir/kei01234kei.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Add kei01234kei.md

---

japan/japan-community-day-2025/workdir/kawakami.md

>
> /kind bug
> /kind design
> /kind flake
Add kawakami.md in to japan/japan-community-day-2025/workdir
Fixes #
```release-note
NONE
```
```docs
```

Add kawakami.md in to japan/japan-community-day-2025/workdir

---

japan/japan-community-day-2025/workdir/74th.md

Add 74th.md to japan/japan-community-day-2025.
Fixes #
```release-note
NONE
```
```docs
```
/sig docs
/sig testing

Add 74th.md to japan/japan-community-day-2025

---

remote/learners/Aarya2004.md

add Aarya2004.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Added account to learners

---

japan/adhoc/workdir/Subaru365.md

Add `Subaru365.md` into japan/adhoc/workdir
Fixes #
```release-note
N/A
```
```docs
```
/sig docs

Add Subaru365.md

---

remote/learners/inkel.md

I'd like to contribute to the Go client.
Fixes #
```release-note
```
```docs
```

Add learners/inkel.md

---

india/remote/learners/gokul.md

>
> /kind bug
> /kind design
> 
> /kind flake
Added gokul.md to the remote learners , for practicing PR submissions
Fixes #
```release-note
NONE
```
```docs
```

added gokul.md to remote learners

---

remote/learners/lisadd.md

add lisadd.md to remote/learners folder for practicing PR submission.
Fixes #
Does this PR introduce a user-facing change?
```
NONE
``` 
```
```

add lisadd.md to remote/learners folder

---

remote/learners/nsunkad.md

add nsunkad.md to remote/learners

---

remote/learners/aleonidex.md

initial commit
>
> /kind bug
> /kind design
> /kind flake
adding a file to remote/learners folder for practicing PR submission and signing CLA.
Fixes #
```release-note
NONE
```
```docs
```

Adding aleonidex.md into remote/learners for CLA purpose

---

remote/learners/maqiuyu

add maqiuyu.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Signing the CLA

---

remote/learners/lzhai.md

>
Create my first pr to sign the CLA
Fixes #
```release-note
NONE
```
```docs
```

Add lzhai.md to remote/leaners

---

remote/learners/rostik_bobo.md

add rostik_bobo.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add rostik_bobo.md to remote/learners folder

---

india/remote/learners/bharath.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

my first commit & first PR in K8s

---

remote/learners/taran.md

Add taran.md to remote/learners folder to practice creating PRs and sign CLA
Fixes #
NONE
```docs
```

add taran.md to remote/learners to sign cla

---

remote/learners/pagwin.md

add pagwin.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add pagwin.md to remote/learners folder

---

remote/learners/edwardviaene.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

checking cla

---

india/remote/learners/virsuryaircas.md

Add virsuryaircas.md to the remote/learners directory for practicing PR submission.
Fixes #
This is a practice PR to help me sign the CLA and learn the Kubernetes contribution process.
```release-note
NONE
```
```docs
NONE
```

Add virsuryaircas to learners directory

---

remote/learners/onasser.md

I need to be accepted as contributor.
Fixes #
```release-note
```
```docs
```

add onasser.md to remote/learners

---

remote/learners/timothy-spencer.md

add timothy-spencer.md to remote/learners folder for practicing PR submission
We need it because change is good!
Fixes #
```release-note
NONE
```
```docs
```

Add timothy-spencer.md page to /remote/learners

---

india/remote/learners/sandeep.md

add sandeep.md to india/remote/learners folder
>
> /kind bug
> /kind design
> /kind flake
add sandeep.md to india/remote/learners folder
Fixes #
```release-note
NONE
```
```docs
```

add sandeep.md to india/remote/learners folder

---

remote/learners/solongandthanksforallthefish.md

>
> /kind bug
> /kind design
> /kind flake
add solongandthanksforallthefish.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

SoLongAndThanksForAllTheFish.md into remote/learners folder

---

remote/learners/tylenwells.md

Just to make sure I've signed the CLA.
Fixes # N/A
N/A
```release-note
NONE
```
```docs
N/A
```

Add tylenwells.md into remote/learners folder

---

remote/learners/pramod.md

add pramod.md to remote/learners folder for practicing PR submission
Fixes #
```release-note
NONE
```
```docs
```

add pramod.md to remote/learners folder

---

remote/learners/mudit.md

Add mudit.md to remote/learners folder, to trigger CLA signing
Fixes #
```release-note
NONE
```
```docs
```

Add mudit.md to remote/learners 

---

brazil/luarch.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
```
```docs
```

Making change to sign the CLA

---

remote/learners/coldinke.md

add coldinke.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
None
```
```docs
```

add coldinke.md to remote/learners folder

---

remote/learners/zohaib.md

Add zohaib.md to remote/learners folder
Add zohaib.md to remote/learners folder for signing the CLA.
```
NONE
```
Fixes #
```
NONE
```
```release-note
NONE
```
```docs
NONE
```

Add zohaib.md to remote/learners folder

---

remote/learners/brianrobt.md

Adding brianrobt.md to remote/learners to practice PR submission.
Fixes #
```release-note
NONE
```
```docs
```

feat(brianrobt.md): add new learner introduction for brianrobt

---

remote/learners/antoine.md

>
> /kind bug
> /kind design
> /kind flake
CLA SIGN
Fixes #
```release-note
```
```docs
```

add antoine.md to remote/learners folder for CLA Signing

---

remote/learners/kamothi.md

>
> /kind bug
> /kind design
> /kind flake
Add kamothi.md to remote/learners folder for signing CLA.
Fixes #
```release-note
none
```
```docs
none
```

Add kamothi.md to remote/learners

---

remote/learners/hankfreund.md

Add hankfreund.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Add hankfreund.md to remote/learners folder.

---

remote/learners/arunkp.md

**What this PR does / why we need it**:  To add arunkp.md to remote/learners folder for PR submission.
**Which issue(s) this PR fixes**: None
Fixes #
**Does this PR introduce a user-facing change?**: No

Add arunkp.md to remote/learners folder

---

india/remote/learners/sats.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NA
```
```docs
NA
```

Add sats.md to india/remote/learners

---

remote/learners/wonyongg.md

>
> /kind bug
> /kind design
> /kind flake
`Add` wonyongg.md to remote/learners for sign CLA.
Fixes #
```release-note
```
```docs
```

Create wonyongg.md to remote/learners

---

remote/learners/rutigs.md

Add rutigs.md to remote/learners for CLA
Fixes #
```release-note
n/a
```
```docs
```

add rutigs.md to remote/learners

---

remote/learners/yomek33.md

add yomek33 into remote learners for learning
Fixes #
```release-note
NONE
```
```docs
```
/sig docs
/sig testing

add yomek33.md into remote/learners

---

remote/learners/mihohoi.md

add mihohoi0322 into remote learners for learning
Fixes #
```release-note
NONE
```
```docs
```
/sig docs
/sig testing

Add mihohoi.md

---

brazil/WagnerFerreira.md

Adiciona minha entrada (dabliof) no diretório `brazil/`, como parte do exercício de contribuição via contributor-playground.
NONE
Este é apenas um Pull Request de teste conforme instruções do repositório `contributor-playground`.
```release-note
NONE

Add brazil/WagnerFerreira.md for registation.

---

brazil/wesleynepo.md

Practicing submitting your first PR
Fixes #
```release-note
NONE
```
```docs
```

add wesleynepo

---

remote/learners/rodrigues-daniel.md

sign the CLA  and  add rodrigues-daniel.md to remote/learners folder for practicing PR submission.
Fixes #
Special notes for your reviewer: 
sign the CLA 
NONE

sign the CLA  and  add rodrigues-daniel.md to remote/learners

---

remote/learners/chetanxrathore.md

add chetanxrathore.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add chetanxrathore.md to remote/learners folder

---

india/remote/learners/khurshid.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
None
```
```docs
None
```

Add khurshid.md to remote/learners

---

remote/learners/Ic-venkat.md

add Ic-venkat.md to remote/learners folder for practicing PR submission.
Fixes #

Ic-venkat.md adding into the contribution.

---

remote/learners/Adilshemsu.md

This PR adds my name file to the learners directory to practice making my first contribution to Kubernetes.
Adds a learner file as a simple first contribution.
None.
None.
NONE
```release-note
NONE

Add shemsu to learners

---

remote/learners/justlorain.md

add justlorain.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add justlorain to remote/learners

---

remote/learners/zeqian-meng.md

To sign CLA and add zeqian-meng.md to remote/learners folder for practicing PR submission
Fixes #
```release-note
None
```
```docs
```

Add zeqian-meng.md to remote/learners

---

remote/learners/dchaloupka.md

Add `dchaloupka.md` to `remote/learners` for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

Add dchaloupka learner

---

remote/learners/ketanjani21.md

sign the CLA and add ketanjani21.md to remote/learners folder for practicing PR submission.
sign the CLA
NONE

Add ketanjani21.md

---

remote/learners/dongbin.md

Add dongbin.md to remote/learners for practicing PR submission.
Fixes #
This is the first PR and is also intended to obtain a CLA.
```release-note
NONE
```
```docs
```

Add greeting for Dongbin in dongbin.md

---

remote/learners/TobyTheHutt.md

add ziyi.md to remote/learners folder for practicing PR submission.
-
-
```release-note
NONE
```
-

Add TobyTheHutt.md to remote/learners

---

remote/learners/rooobinye.md

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```release-note
NONE
```
```docs
```

feat: add rooobinye.md

---

remote/learners/veepeeaee.md

add veepeeaee.md to remote/learners for first PR and signing CLA
Fixes #
```release-note
NONE
```
```docs
```

Adding veepeeaee to remote/learners

---

remote/learners/YangHgRi.md

add YangHgRi.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add YangHgRi.md to remote/learners folder

---

remote/learners/9999dude.md

Add 9999dude.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
NONE
```
```docs
```

add 9999dude.md to remote/learners folder

---

remote/learners/Hefeeder.md

**What this PR does / why we need it**: add Hefeeder.md to remote/learners folder for practicing PR submission.
Fixes #
```
NONE
```
```
```

add Hefeeder.md to remote/learners folder

---

remote/learners/shubhanshu.md

adds a new .md file in /remote/learners folder for practice.
Fixes #
```release-note
NONE
```
```docs
```

Create shubhanshu.md to remote/learners

---

remote/learners/hirokei.md

add hirokei.md to remote/learners folder for practicing PR submission.
Fixes #
```release-note
```
```docs
```

Create hirokei.md for CLA

---

japan/OWNERS

/kind cleanup
Added mochizuki875 as KUTJ organizer.
Also, aligned in alphabetic order.
Fixes #
@mochizuki875 
```release-note
NONE
```
```docs
```

Add mochizuki875 into OWNERS file
